---
title: "graph-to-total-parallel"
author: "Olivier GAUFRÈS"
date: "2024-04-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(dplyr)
library(Rcpp)
library(RcppParallel)
```


## Data import
```{r}
wd <- getwd()
knitr::opts_chunk$set(root.dir = wd)

simplified_path <- file.path(wd, "..", "..", "data", "data-simplified")
graph_1 <- read.csv2(file = file.path(simplified_path, "graph_1.csv"), header = TRUE, sep = ";") %>% 
                      mutate(date_posix = as.POSIXct(x = date_posix, format = "%Y-%m-%d %H:%M:%S"))
```


## Consts
```{r}
begin_date <- as.POSIXct("2009-07-06 00:00:00")
end_date <- as.POSIXct("2009-09-28 00:00:00")
time_spent <- end_date - begin_date
n_subdivisions <- as.integer(time_spent) * 24 * 60 * 2 ## Time spent * hours * minutes * 2 (number of time subdivisions)
```

## Test parralel
```{r}
# Call the parallel function
sourceCpp(file.path(wd,"..", "..","cpp","test-parallel.cpp"))

```

```{r}
interactions_tot <- NULL
setThreadOptions(numThreads = defaultNumThreads())
para_a <- Sys.time()
interactions_tot_cpp <- parallelInteractions(date_posix = graph_1$date_posix,
                                         length = graph_1$length,
                                         from = graph_1$from,
                                         to = graph_1$to,
                                         begin_date = begin_date,
                                         n_subdivisions = 130)
para_b <- Sys.time()
print(para_b-para_a)
```

## Errors in the past (previous codes)
```{r}
# Erreur : logical subsetting requires vectors of identical size
# Erreur : plus de gestionnaire d'erreur disponible (erreurs récursives ? ) ;  appel d'un redémarrage de type 'abort'
# Erreur dans .Call(<pointer: (nil)>, date_posix, length, from, to, begin_date,  : Valeur NULL passée comme adresse symbolique
# write.csv2(interactions_tot, file = file.path(wd,"..", "..", "data", "data-expanded", "graph-1-int-1-to-end-cpp.csv"))
# Line 31cannot convert 'double' to 'const char*'
# Line 41cannot convert 'std::__cxx11::basic_string<char>' to 'const char*'
```

## Non parallel
```{r}

interactions_tot_R <- data.frame(from = NA, to = NA, time = NA)
lin_a <- Sys.time()
for(t in 1:140){
  interactions_t <- graph_1 %>%
    filter(date_posix <= begin_date + (t)*30 & date_posix + length >= begin_date + (t+1)*30) %>%
    mutate(time = t) %>%
    select(from, to, time)

  if (dim(interactions_t)[1]!= 0){
  interactions_tot_R <- interactions_tot_R %>% bind_rows(interactions_t)
  }
}
lin_b <- Sys.time()
print("Time RcppParallel")
print(para_b-para_a)
print("Time R (linear)")
print(lin_b-lin_a)
# write.csv2(interactions_tot, file = file.path(wd,"..", "..", "data", "data-expanded", "graph-1-int-1-to-end-R.csv"))
```


