---
title: "Network simplifier"
author: "Olivier GAUFRÈS"
date: "2024-04-11"
output: html_document
---

## Libraries
```{r eval=false}
library(dplyr)
library(readxl)
```

```{r}
wd <- getwd()
knitr::opts_chunk$set(root.dir = wd)
data_ibird_path <-  file.path(wd,"..", "..", "data","data-i-bird")
observed_path <- file.path(data_ibird_path, "data-observed")
simplified_path <- file.path(data_ibird_path,"data-simplified")
synthetic_path <- file.path(data_ibird_path, "data-synthetic")
expanded_path <- file.path(data_ibird_path, "data-expanded")

## xlsx files
cat_groupings <- read_excel(path = file.path(observed_path,"cat_groupings.xlsx"), col_names= TRUE)

## csv files
toy_admission <- read.csv2(file = file.path(observed_path, "toy_admission.csv"), header = TRUE, sep = ";")
toy_agenda <- read.csv2(file = file.path(observed_path, "toy_agenda.csv"), header = TRUE, sep = ";")
toy_mat_ctc <- read.csv2(file = file.path(observed_path, "toy_mat_ctc.csv"), header = TRUE, sep = ";")
```


## Sorting according to our assumptions
```{r}
## We only keep interactions between individuals of the same ward. Thus, the individuals that had an inter-ward interaction, they will now have no interaction (cross-ward's infection will be taken into account with \alpha parameter)
chosen_ward <- "Menard 1" ## Ward of our choice


admission <- filter(toy_admission, ward == chosen_ward)
write.csv2(admission, file = file.path(simplified_path, "admission.csv"), sep = ";", row.names = FALSE)

agenda <- filter(toy_agenda, ward == chosen_ward)
write.csv2(agenda, file = file.path(simplified_path, "agenda.csv"), sep = ";", row.names = FALSE)

mat_ctc <- filter(toy_mat_ctc, from %in% admission$id & to %in% admission$id) ## Both induviduals must be from the same ward
write.csv2(mat_ctc, file = file.path(simplified_path, "mat_ctc.csv"), sep = ";", row.names = FALSE)
```


## Sorting the synthetic graphs according to our assumptions
```{r}
list_graph <- list.files(path = file.path(synthetic_path))
dir.create(file.path(wd,"..", "data", "data-simplified"))
```


```{r}
for (i in seq_along(list_graph)){
  index <- gsub("[^0-9]", "", list_graph[i])
  df <- read.csv2(file = file.path(synthetic_path, list_graph[i]), header = TRUE)
  df <- df %>% filter(from %in% admission$id & to %in% admission$id) 
  write.csv2(df, file = file.path(simplified_path, paste0("graph_", index, ".csv")), row.names = FALSE)
  print(paste0("File ", index, " written in: ", file.path(simplified_path, paste0("graph_", index, ".csv"))))
}

# ## Example of a synthetic graph before reducing it to only a ward
# toy_graph <- read.csv2(file = file.path(synthetic_path, list_graph[1]), header = TRUE)
# # To compare
# dim(toy_graph)[1] - dim(graph_1)[1]
# dim(toy_admission)[1] - dim(admission)[1]
```







