*---
title: "Untitled"
author: "Olivier GAUFRÈS"
date: "2024-04-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
wd <- getwd()
knitr::opts_chunk$set(root.dir = wd)
library(openxlsx)
library(here)
library(dplyr)
library(lubridate)
library(ggnetwork)
library(ggtext)
library(cowplot)
library(RColorBrewer)
library(igraph)

## Functions for graph analysis (https://github.com/qleclerc/network_algorithm/)
## Following script based on https://github.com/qleclerc/network_algorithm/blob/main/analysis/fig1.R
source(file.path("helper_functions.R"))

## i-Bird color palette
pal = brewer.pal(6, "Set2")
```

## Data import (i-Bird)
```{r}
adm_data = read.csv(file.path(wd, "..", "..", "data", 'data-i-bird', "data-observed", "toy_admission.csv"), sep=";") %>%
  select(id, hospitalization, cat, ward)
adm_data$cat[adm_data$cat == ""] = adm_data$hospitalization[adm_data$cat == ""]
adm_data = adm_data[,c(1,3,4)] %>%
  distinct()
eq_table = openxlsx::read.xlsx(file.path(wd, "..", "..","data", 'data-i-bird',"data-observed", "cat_groupings.xlsx")) %>%
  select(cat, cat_ag)
adm_data = adm_data %>%
  left_join(eq_table, by = "cat") %>%
  mutate(staff = grepl("PE-", id))

data = read.csv2(file.path(wd, "..", "..","data", 'data-i-bird',"data-simplified", "graph_1.csv"))
```

## Data import (NodsCov2)
```{r}
load(file.path(wd, "..", "..", "data","data-nodscov2", "admission_ctc_nodscov2.RData"))
Encoding(admission$hospital) <- 'latin1'
## FILTER TO KEEP ONLY RP ICU
admission <- admission %>% filter(hospital == 'APHP - RAYMOND POINCARÉ',
                                  ward == 'Reanimation')



## TYPE OF INDIVIDUALS
admission %>% distinct(cat) %>% pull()
cat_paramedical <- c("nurse", "student nurse", "aux nurse")
cat_medical <- c("physician", "ext physician", "reeducation staff", "other")
id_paramedical <- admission %>% filter(cat %in% cat_paramedical) %>% pull(id)
id_medical <- admission %>% filter(cat %in% cat_medical) %>% pull(id)
id_patient <- admission %>% filter(status == "PA") %>% pull(id)


adm_data = admission %>%
  ## Filter to remove administration, logistic, visitors...
  filter((id %in% id_patient | id %in% id_medical | id %in% id_paramedical)) %>% 
  ## ADD PE/PA TO THE ID
  mutate(id = paste0(status, '-', id)) %>%
  select(id, hospitalization, cat, ward)

adm_data$cat[is.na(adm_data$cat)] = adm_data$hospitalization[is.na(adm_data$cat)]
adm_data = adm_data[,c(1,3,4)] %>%
  distinct()

## ADDING PATIENT / PARAMEDICAL / MEDICAL
adm_data <- adm_data %>%
  mutate(type = case_when(
    substr(id,4,100) %in% id_paramedical ~ "Paramedical",
    substr(id,4,100) %in% id_medical ~ "Medical",
    substr(id,4,100) %in% id_patient ~ "Patient",
    .default = "Other"
  ))
adm_data$type <- factor(adm_data$type, levels = c("Medical", "Paramedical", "Patient"))

### COLOR PALETTES /!\ to factor order
## Nodscov2 color palette
pal = brewer.pal(4, "Set2")
## Epicontact infection network color palette (B3 -> HEX CODE FOR ALPHA = 70%)
pal = c("#5CD6D6B3", "#A9B9E8B3", "#FFA766B3", "#666699B3")
## ALPHA = 1 
pal = c("#5CD6D6", "#A9B9E8", "#FFA766", "#666699")
names(pal) <- c('MEDICAL', 'PARAMEDICAL', 'PATIENT', 'ROOM')
## Category groupings
eq_table = openxlsx::read.xlsx(file.path(wd, "..", "..","data", 'data-nodscov2', "cat_groupings_nodscov2.xlsx")) %>%
  select(cat, cat_ag)
adm_data = adm_data %>%
  left_join(eq_table, by = "cat") %>%
  mutate(staff = grepl("PE-", id))


## INTERACTION DATA
load(file.path(wd, "..", "..", "data","data-nodscov2", "list_ward.RData"))
data = list_ward[["Raymond_Poincare-Reanimation-20200506-20200507"]] %>% mutate(date_posix = date_posix_first)

## ## Filter to remove administration, logistic, visitors...
data <- data %>% filter( (from %in% id_patient | from %in% id_medical | from %in% id_paramedical) &
                (to %in% id_patient | to %in% id_medical | to %in% id_paramedical))

## ADD PA/PE to ids
data <- left_join(data, admission %>% select(id, status), by = c("from" = "id")) %>%
  rename(from_status = status) %>%
  left_join(admission %>% select(id, status), by = c("to" = "id")) %>%
  rename(to_status = status) %>%
  mutate(from = paste0(from_status, '-', from), to = paste0(to_status, '-', to)) %>%
  select(from, to, date_posix, length)
```



```{r}
##i-Bird dates limits
begin_limit <- "2009-07-27"
end_limit <-  "2009-08-24"

##Nodscov2 dates limits
begin_limit <- "2020-05-06"
end_limit <- "2020-05-08"


## GRAPH DATA FOR THE ENTIRE STUDY PERIOD
graph_data = data %>%
  mutate(date_posix = as_datetime(date_posix)) %>%
  mutate(date_posix = floor_date(date_posix, "day")) %>%
  filter(date_posix >= as_date(begin_limit) & date_posix < as_date(end_limit)) %>%
  group_by(from, to, date_posix) %>%
  summarise(length = sum(length)) %>%
  ungroup %>%
  arrange(date_posix)

## GRAPH DATA FOR THE TRUNCATED STUDY PERIOD
begin_date <- as.POSIXct("2020-05-06 12:00:00")
end_date <- as.POSIXct("2020-05-07 12:00:00")

graph_data_trunc = data %>% 
  filter(as.POSIXct(date_posix) + length >= begin_date) %>%
  filter(as.POSIXct(date_posix) < end_date) %>%
  mutate(date_posix = as_datetime(date_posix)) %>%
  mutate(date_posix = floor_date(date_posix, "day")) %>%
  filter(date_posix >= as_date(begin_limit) & date_posix < as_date(end_limit)) %>%
  group_by(from, to, date_posix) %>%
  summarise(length = sum(length)) %>%
  ungroup %>%
  arrange(date_posix)

graph_data_PA_PA = graph_data %>%
  filter(grepl("PA-", from) & grepl("PA-", to))

graph_data_PE_PE = graph_data %>%
  filter(grepl("PE-", from) & grepl("PE-", to))

graph_data_PA_PE = graph_data %>%
  filter((grepl("PE-", from) & grepl("PA-", to)) | (grepl("PA-", from) & grepl("PE-", to)))
```

## Metrics
```{r}
all_metrics = get_net_metrics(graph_data, network = "Full")

PA_PA_metrics = get_net_metrics(graph_data_PA_PA, network = "PA-PA")
PE_PE_metrics = get_net_metrics(graph_data_PE_PE, network = "PE-PE")
PA_PE_metrics = get_net_metrics(graph_data_PA_PE, network = "PA-PE")

cols = colnames(all_metrics)[1:7]
summary_tab = rbind(all_metrics, PA_PA_metrics, PE_PE_metrics, PA_PE_metrics) %>%
  mutate(temp_corr = replace(temp_corr, temp_corr==0, NA)) %>%
  group_by(network) %>%
  summarise(across(all_of(cols), list(mean=mean, sd=sd), na.rm=T))

summary_tab[,-1] = round(summary_tab[,-1], 2)

View(summary_tab)
```

## Coefficient of variation
```{r}
## CV ACROSS THE ENTIRE STUDY PERIOD
all_degrees = c()
for(d in unique(graph_data$date_posix)){
  data_d = graph_data %>%
    filter(date_posix == d)
  
  graph_d = graph_from_data_frame(data_d, directed = F)
  graph_d = simplify(graph_d)
  all_degrees = c(all_degrees, degree(graph_d))
}

pe = ggplot() +
  geom_histogram(aes(all_degrees, after_stat(density)), binwidth = 1, colour = "grey") +
  geom_vline(xintercept = mean(all_degrees), linetype = "dashed", linewidth = 1, colour = "red3") +
  geom_richtext(aes(x = 70, y = 0.05,
                    label = paste0("CV<sup>2</sup> = ",
                                   round((sd(all_degrees)/mean(all_degrees))^2, 2))),
                colour = "red3", size = 5) +
  theme_bw() +
  labs(x = "Node degree", y = "Frequency") +
  theme(axis.text = element_text(size = 12),
        axis.title = element_text(size = 12)) +
  scale_x_continuous(breaks = seq(0,70,10))


## CV ACROSS THE TRUNCATED STUDY PERIOD FOR NODSCOV2 RP ICU
all_degrees = c()
for(d in unique(graph_data_trunc$date_posix)){
  data_d = graph_data_trunc %>%
    filter(date_posix == d)
  
  graph_d = graph_from_data_frame(data_d, directed = F)
  graph_d = simplify(graph_d)
  all_degrees = c(all_degrees, degree(graph_d))
}

pe = ggplot() +
  geom_histogram(aes(all_degrees, after_stat(density)), binwidth = 1, colour = "grey") +
  geom_vline(xintercept = mean(all_degrees), linetype = "dashed", linewidth = 1, colour = "red3") +
  geom_richtext(aes(x = 40, y = 0.07,
                    label = paste0("CV<sup>2</sup> = ",
                                   round((sd(all_degrees)/mean(all_degrees))^2, 2))),
                colour = "red3", size = 5) +
  theme_bw() +
  labs(x = "Node degree", y = "Frequency") +
  theme(axis.text = element_text(size = 12),
        axis.title = element_text(size = 12)) +
  scale_x_continuous(breaks = seq(0,40,10))
```


### Building graphs

## Arbitrary date
```{r}
##i Bird Arbitrary date
arbitrary_date <- "2009-07-28"
## Nodscov 2 Arbitrary date
arbitrary_date <- "2020-05-06"


example_date = as_date(arbitrary_date)
example_data = data %>% filter(as_date(date_posix) == example_date) ## was date_posix only --> filters to 0 ??

## FILTER TO KEEP ONLY TRUNCATED DATA FROM RAYMOND POINCARÉ ICU
example_data = data %>% 
  filter(as.POSIXct(date_posix) + length >= begin_date) %>%
  filter(as.POSIXct(date_posix) < end_date)
```

## Full graph
```{r}
# full
graph_example = graph_from_data_frame(example_data, directed = F)
graph_example = simplify(graph_example)

vertex_atts = data.frame(id = get.vertex.attribute(graph_example, "name")) %>%
  left_join(adm_data, "id") %>%
  mutate(ward = replace(ward, ward == "Menard 1", "Neurologic (1)"),
         ward = replace(ward, ward == "Menard 2", "Neurologic (2)"),
         ward = replace(ward, ward == "Sorrel 0", "Nutrition"),
         ward = replace(ward, ward == "Sorrel 1", "Neurologic (3)"),
         ward = replace(ward, ward == "Sorrel 2", "Geriatric"),
         ward = replace(ward, ward == "Other", "Mobile"))

graph_example = graph_example %>%
  set_vertex_attr("cat", value = vertex_atts$cat) %>%
  set_vertex_attr("cat_ag", value = vertex_atts$cat_ag) %>%
  set_vertex_attr("staff", value = vertex_atts$staff) %>%
  set_vertex_attr("ward", value = vertex_atts$ward) %>%
  set_vertex_attr("type", value = vertex_atts$type) 
  
```

## PA-PA graph
```{r}
# PA-PA
graph_example_PA_PA = graph_from_data_frame(graph_data_PA_PA %>% filter(date_posix == example_date),
                                            directed = F)
graph_example_PA_PA = simplify(graph_example_PA_PA)

vertex_atts = data.frame(id = get.vertex.attribute(graph_example_PA_PA, "name")) %>%
  left_join(adm_data, "id") %>%
  mutate(ward = replace(ward, ward == "Menard 1", "Neurologic (1)"),
         ward = replace(ward, ward == "Menard 2", "Neurologic (2)"),
         ward = replace(ward, ward == "Sorrel 0", "Nutrition"),
         ward = replace(ward, ward == "Sorrel 1", "Neurologic (3)"),
         ward = replace(ward, ward == "Sorrel 2", "Geriatric"),
         ward = replace(ward, ward == "Other", "Mobile"))

graph_example_PA_PA = graph_example_PA_PA %>%
  set_vertex_attr("cat", value = vertex_atts$cat) %>%
  set_vertex_attr("cat_ag", value = vertex_atts$cat_ag) %>%
  set_vertex_attr("staff", value = vertex_atts$staff) %>%
  set_vertex_attr("ward", value = vertex_atts$ward) %>%
  set_vertex_attr("type", value = vertex_atts$type) 
```

## PE-PE graph
```{r}
# PE-PE
graph_example_PE_PE = graph_from_data_frame(graph_data_PE_PE %>% filter(date_posix == example_date),
                                            directed = F)
graph_example_PE_PE = simplify(graph_example_PE_PE)

vertex_atts = data.frame(id = get.vertex.attribute(graph_example_PE_PE, "name")) %>%
  left_join(adm_data, "id") %>%
  mutate(ward = replace(ward, ward == "Menard 1", "Neurologic (1)"),
         ward = replace(ward, ward == "Menard 2", "Neurologic (2)"),
         ward = replace(ward, ward == "Sorrel 0", "Nutrition"),
         ward = replace(ward, ward == "Sorrel 1", "Neurologic (3)"),
         ward = replace(ward, ward == "Sorrel 2", "Geriatric"),
         ward = replace(ward, ward == "Other", "Mobile"))

graph_example_PE_PE = graph_example_PE_PE %>%
  set_vertex_attr("cat", value = vertex_atts$cat) %>%
  set_vertex_attr("cat_ag", value = vertex_atts$cat_ag) %>%
  set_vertex_attr("staff", value = vertex_atts$staff) %>%
  set_vertex_attr("ward", value = vertex_atts$ward) %>%
  set_vertex_attr("type", value = vertex_atts$type) 
```

## PA-PE graph
```{r}
# PA-PE
graph_example_PA_PE = graph_from_data_frame(graph_data_PA_PE %>% filter(date_posix == example_date),
                                            directed = F)
graph_example_PA_PE = simplify(graph_example_PA_PE)

vertex_atts = data.frame(id = get.vertex.attribute(graph_example_PA_PE, "name")) %>%
  left_join(adm_data, "id") %>%
  mutate(ward = replace(ward, ward == "Menard 1", "Neurologic (1)"),
         ward = replace(ward, ward == "Menard 2", "Neurologic (2)"),
         ward = replace(ward, ward == "Sorrel 0", "Nutrition"),
         ward = replace(ward, ward == "Sorrel 1", "Neurologic (3)"),
         ward = replace(ward, ward == "Sorrel 2", "Geriatric"),
         ward = replace(ward, ward == "Other", "Mobile"))

graph_example_PA_PE = graph_example_PA_PE %>%
  set_vertex_attr("cat", value = vertex_atts$cat) %>%
  set_vertex_attr("cat_ag", value = vertex_atts$cat_ag) %>%
  set_vertex_attr("staff", value = vertex_atts$staff) %>%
  set_vertex_attr("ward", value = vertex_atts$ward) %>%
  set_vertex_attr("type", value = vertex_atts$type) 
```

## Plots (nodes colored by ward)
```{r}
pa = ggplot(ggnetwork(graph_example, layout = igraph::layout_with_kk(graph_example)),
            aes(x = x, y = y, xend = xend, yend = yend)) +
  geom_edges(alpha = 0.5) +
  geom_nodes(aes(colour = ward, shape = staff), size = 4) +
  theme_blank() +
  scale_shape_manual(breaks = c("TRUE", "FALSE"), labels = c("Staff", "Patients"),
                     values = c(15,17)) +
  scale_colour_discrete(type = pal) +
  labs(colour = "Ward:", shape = "Category:") +
  theme(legend.text = element_text(size=12))

pb = ggplot(ggnetwork(graph_example_PA_PA, layout = igraph::layout_with_kk(graph_example_PA_PA)),
            aes(x = x, y = y, xend = xend, yend = yend)) +
  geom_edges(alpha = 0.5) +
  geom_nodes(aes(colour = ward, shape = staff), size = 3) +
  theme_blank() +
  scale_shape_manual(breaks = c("TRUE", "FALSE"), labels = c("Staff", "Patients"),
                     values = c(15,17)) +
  scale_colour_discrete(type = pal[-2]) +
  labs(colour = "Ward:", shape = "Category:") +
  theme(legend.text = element_text(size=12)) +
  guides(shape = "none", colour = "none")

pc = ggplot(ggnetwork(graph_example_PE_PE, layout = igraph::layout_with_kk(graph_example_PE_PE)),
            aes(x = x, y = y, xend = xend, yend = yend)) +
  geom_edges(alpha = 0.5) +
  geom_nodes(aes(colour = ward, shape = staff), size = 3) +
  theme_blank() +
  scale_shape_manual(breaks = c("TRUE", "FALSE"), labels = c("Staff", "Patients"),
                     values = c(15,17)) +
  scale_colour_discrete(type = pal) +
  labs(colour = "Ward:", shape = "Category:") +
  theme(legend.text = element_text(size=12)) +
  guides(shape = "none", colour = "none")

pd = ggplot(ggnetwork(graph_example_PA_PE, layout = igraph::layout_with_kk(graph_example_PA_PE)),
            aes(x = x, y = y, xend = xend, yend = yend)) +
  geom_edges(alpha = 0.5) +
  geom_nodes(aes(colour = ward, shape = staff), size = 3) +
  theme_blank() +
  scale_shape_manual(breaks = c("TRUE", "FALSE"), labels = c("Staff", "Patients"),
                     values = c(15,17)) +
  scale_colour_discrete(type = pal) +
  labs(colour = "Ward:", shape = "Category:") +
  theme(legend.text = element_text(size=12)) +
  guides(shape = "none", colour = "none")
```

## Plots (nodes colored by type)
```{r}
pa = ggplot(ggnetwork(graph_example, layout = igraph::layout_with_kk(graph_example)),
            aes(x = x, y = y, xend = xend, yend = yend)) +
  geom_edges(alpha = 0.5) +
  geom_nodes(aes(colour = type, shape = staff), size = 4) +
  theme_blank() +
  scale_shape_manual(breaks = c("TRUE", "FALSE"), labels = c("Staff", "Patients"),
                     values = c(15,17)) +
  scale_colour_discrete(type = pal) +
  labs(colour = "Type:", shape = "Category:") +
  theme(legend.text = element_text(size=12))

pb = ggplot(ggnetwork(graph_example_PA_PA, layout = igraph::layout_with_kk(graph_example_PA_PA)),
            aes(x = x, y = y, xend = xend, yend = yend)) +
  geom_edges(alpha = 0.5) +
  geom_nodes(aes(colour = type, shape = staff), size = 3) +
  theme_blank() +
  scale_shape_manual(breaks = c("TRUE", "FALSE"), labels = c("Staff", "Patients"),
                     values = c(15,17)) +
  scale_colour_discrete(type = pal[-c(1,2,4)]) + ## PATIENT COLOR -> factor
  labs(colour = "Type:", shape = "Category:") +
  theme(legend.text = element_text(size=12)) +
  guides(shape = "none", colour = "none")

pc = ggplot(ggnetwork(graph_example_PE_PE, layout = igraph::layout_with_kk(graph_example_PE_PE)),
            aes(x = x, y = y, xend = xend, yend = yend)) +
  geom_edges(alpha = 0.5) +
  geom_nodes(aes(colour = type, shape = staff), size = 3) +
  theme_blank() +
  scale_shape_manual(breaks = c("TRUE", "FALSE"), labels = c("Staff", "Patients"),
                     values = c(15,17)) +
  scale_colour_discrete(type = pal) +
  labs(colour = "Type:", shape = "Category:") +
  theme(legend.text = element_text(size=12)) +
  guides(shape = "none", colour = "none")

pd = ggplot(ggnetwork(graph_example_PA_PE, layout = igraph::layout_with_kk(graph_example_PA_PE)),
            aes(x = x, y = y, xend = xend, yend = yend)) +
  geom_edges(alpha = 0.5) +
  geom_nodes(aes(colour = type, shape = staff), size = 3) +
  theme_blank() +
  scale_shape_manual(breaks = c("TRUE", "FALSE"), labels = c("Staff", "Patients"),
                     values = c(15,17)) +
  scale_colour_discrete(type = pal) +
  labs(colour = "Type:", shape = "Category:") +
  theme(legend.text = element_text(size=12)) +
  guides(shape = "none", colour = "none")
```

## Figure export
```{r}
plot_grid(pa,
          plot_grid(pb,pc,pd,nrow=1, labels = c("B", "C", "D"), hjust = 0),
          pe, rel_heights = c(1,0.7,0.5), ncol = 1, labels = c("A", "", "E"), hjust = 0)

#ggsave(file.path(wd, "..", "..", "Figures", "fig1-ibird.png"), height = 12, width = 10)
ggsave(file.path(wd, "..", "..", "out", "fig", "fig1-nodscov2-RP-ICU.png"), height = 12, width = 12)
```

