---
title: "CSV-to-model"
author: "Olivier GAUFRÈS"
date: "2024-05-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(Rcpp)
```

```{r paths}
wd <- getwd()
knitr::opts_chunk$set(root.dir = wd)
args = commandArgs(trailingOnly=TRUE)


data_path <- file.path(wd,"..", "..", "data")
observed_path <- file.path(data_path,"data-observed")
synthetic_path <- file.path(data_path, "data-synthetic-graphs")
simplified_path <- file.path(data_path, "data-simplified")
expanded_path <- file.path(data_path,"data-expanded")
nodscov2_path <- file.path(data_path, "data-nodscov2") 

cpp_path <-  file.path(wd,"..", "..", "cpp")
cpp_model_path <- file.path(cpp_path,"nodscov2")
sim_nodscov2_path <- file.path(wd, "..", "..", "out", "sim-nodscov2")
loc_nodscov2_path <- file.path(wd, "..", "..", "out", "loc-nodscov2")
```

## Load data
```{r}
list_ward <- read.csv(file.path(nodscov2_path, "Private", "list_ward_complete.csv" ))
admission <- read.csv(file.path(nodscov2_path ,"Private", "id_function_complete.csv"))
# list_ward <- read.csv(file.path(nodscov2_path, "list_ward_partial.csv"))
# admission <- read.csv(file.path(nodscov2_path, "id_function_partial.csv"))
```

