---
title: "test-gif"
author: "Olivier GAUFRÈS"
date: "2024-06-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(gganimate)
library(gifski)
```

```{r Paths setup}
wd <- getwd()
knitr::opts_chunk$set(root.dir = wd)


data_path <- file.path(wd,"..", "..", "data")
nodscov2_path <- file.path(data_path, "data-nodscov2") 
loc_nodscov2_path <- file.path(wd, "..", "..", "out", "loc-nodscov2")
fig_path <- file.path(loc_nodscov2_path,"..","fig")
ind_paths_path <- file.path(fig_path, "individual-paths")


if (!dir.exists(data_path)) {
  dir.create(data_path, recursive = TRUE)
}
if (!dir.exists(nodscov2_path)) {
  dir.create(nodscov2_path, recursive = TRUE)
}
if (!dir.exists(loc_nodscov2_path)) {
  dir.create(loc_nodscov2_path, recursive = TRUE)
}
if (!dir.exists(fig_path)) {
  dir.create(fig_path, recursive = TRUE)
}
if (!dir.exists(ind_paths_path)) {
  dir.create(ind_paths_path, recursive = TRUE)
}

```

```{r}
load(file.path(loc_nodscov2_path,"dev-localization-nodscov2.RData")) ##overwrite admission
```

```{r}
chambres <- data.frame(
  localization = 1:24,
  x = c(1, 2, 3, 4, 5, 6, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 16, 18, 19, 20, 21, 22, 23),
  y = c(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 4, 4, 3, 3, 2, 5),
  type = c(rep("Chambre", 18), rep("Restrooms", 2), rep("Office/Nursing station",2), "Corridor", "Only MED+PARAMED")
)

all_data <- do.call(rbind,global_localization) %>% filter(time < 30)
all_data <- all_data %>%
  filter(localization != -1) %>%
  left_join(chambres, by = c("localization")) %>% 
  left_join(admission, by = c("id")) %>% 
  mutate(cat = ifelse(is.na(cat), "patient", cat)) %>% 
  filter(cat != "patient")
```

```{r}
p <- ggplot(all_data, aes(x = x, y = y, color = factor(id), group = id)) +
  geom_point(size = 5) +
  geom_path(aes(group = id), alpha = 0.8) +  # Tracer les trajectoires
  scale_color_discrete(name = "Individu") +
  scale_y_continuous(breaks = 1:5, labels = c("Chambre", "Corridor", "Office", "Restroom", "Med + PM")) +
  labs(title = 'Déplacement des individus au temps: {frame_time}', x = 'X', y = 'Type de pièce') +
  theme_minimal()
```

```{r}
animation <- p + 
  transition_time(time) +
  ease_aes('linear')
```

```{r, echo = FALSE}
animate(animation, renderer = gifski_renderer("deplacement.gif"), width = 2000, height = 1333, duration = 60)
```

