---
title: "dev-figures-loc-nodscov2"
author: "Olivier GAUFRÈS"
date: "2024-07-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(lubridate)
library(igraph)
library(tidyr)
library(viridis)
library(purrr)
library(stringr)
```

```{r Paths setup}
wd <- getwd()
knitr::opts_chunk$set(root.dir = wd)
data_path <- file.path(wd,"..", "..", "data")
nodscov2_path <- file.path(data_path, "data-nodscov2") 
loc_nodscov2_path <- file.path(wd, "..", "..", "out", "loc-nodscov2")
fig_path <- file.path(loc_nodscov2_path,"..","fig")
ind_paths_path <- file.path(fig_path, "individual-paths")
if (!dir.exists(ind_paths_path)) {
  dir.create(ind_paths_path, recursive = TRUE)
}
if (!dir.exists(loc_nodscov2_path)) {
  dir.create(loc_nodscov2_path, recursive = TRUE)
}
if (!dir.exists(fig_path)) {
  dir.create(fig_path, recursive = TRUE)
}
if (!dir.exists(nodscov2_path)) {
  dir.create(nodscov2_path, recursive = TRUE)
}
```

```{r}
load(file.path(loc_nodscov2_path,"dev-localization-nodscov2.RData"))
```


```{r IDS interactings}
## IDS INTERACTING
id_interacting <- do.call(rbind, global_interaction) %>%
  pivot_longer(cols = c(from, to), names_to = "direction", values_to = "individual") %>% distinct(individual) %>% pull()
id_total <- admission %>% distinct(id) %>% pull()
id_not_interacting <- setdiff(id_total, id_interacting)

admission %>% distinct(cat) %>% pull()
cat_paramedical <- c("nurse", "student nurse", "aux nurse")
cat_medical <- c("physician", "ext physician", "reeducation staff", "other")
## IDS BY CATEGORY
id_paramedical <- admission %>% filter(id %in% id_interacting & cat %in% cat_paramedical) %>% pull(id)
id_medical <- admission %>% filter(id %in% id_interacting & cat %in% cat_medical) %>% pull(id)
id_hcw <- admission %>% filter(id %in% id_interacting & status == "PE") %>% pull(id)
id_patient <- admission %>% filter(id %in% id_interacting & status == "PA") %>% pull(id)

id_room_patient <- rooms %>% 
  filter(id %in% (admission %>% filter(status == "PA") %>% pull(id))) %>%
  distinct(id_room) %>%
  pull()
```



## CUMULATIVE NUMBER OF INTERACTION OVER TIME
```{r}


p_number_int <- do.call(rbind, global_interaction) %>%
  mutate(type_int = paste0(from_status, "-", to_status)) %>%
  mutate(type_int = ifelse(type_int == "PA-PE", "PE-PA", type_int)) %>%
  filter(type_int != "PA-PA") %>%
  #filter(between(time,600, 600 + 24*60*2)) %>%
  group_by(time, type_int) %>%
  summarise(n = n()) %>%
  ggplot(aes(x=begin_date + time*30, y=n, color = type_int))+
    geom_line(linewidth = 0.3) +
    annotate("rect", xmin = as.POSIXct("2020-05-06 12:00:00"), xmax = as.POSIXct("2020-05-07 12:00:00"), ymin = -Inf, ymax = Inf, alpha = 0.3, fill = "lightgrey") +  
    annotate("rect", xmin = as.POSIXct("2020-05-06 22:00:00"), xmax = as.POSIXct("2020-05-07 06:00:00"), ymin = -Inf, ymax = Inf, alpha = 0.2, fill = "darkgrey") +
  
    theme_bw() +
    theme(axis.text.x = element_text(angle = 35, hjust = 1)) +
    labs(x = "Time", y = "Number of interactions", color = "Type of interaction") +
    # labs(title = "Number of interaction over time") +
    scale_color_manual(values = c("PE-PA" = "orange", "PE-PE" = "purple"), 
                       labels = c("PE-PA" = "Patient - HCW", 
                                  "PE-PE" = "HCW - HCW"))

print(p_number_int)
ggsave(file = file.path(fig_path, paste0("p_number_int", ".png")), plot = p_number_int, height = 3, width = 12)
```


## DISTRIBUTION OF TIME SPENT IN RESTROOM/CORRIDOR BY CATEGORY OF HCW
```{r Time spent in Restroom/Corridor by HCW cat}
## TRUNCATE TO KEEP ONLY 24H (24/05/06 12:00 TO 24/05/07 12:00)
end_date - begin_date ##end of last interaction
new_begin_date <- begin_date + (5*60*60) ## OFFSET TO START THE DAY AT 12AM
new_end_date <- new_begin_date + (24*60*60)
print(new_end_date - new_begin_date)
t_begin <- 5*60*2 ## OFFSET t
t_end <- (t_begin + 24*60*2) - 1

load(file.path(loc_nodscov2_path,"dev-localization-nodscov2.RData")) ##overwrite admission

global_localization_bis <- global_localization

test_loc <- do.call(rbind, global_localization) %>%
  filter(between(time, 600, 600+2880)) %>%
  left_join(admission %>% select(id, cat), by = join_by(id)) %>% 
  left_join(rooms %>% distinct(id_room, .keep_all = T) %>% select(id_room, room), by = c("localization" = "id_room")) %>%
  mutate(type = ifelse(id %in% id_medical , "MEDICAL", NA)) %>%
  mutate(type = ifelse(id %in% id_paramedical , "PARAMEDICAL", type)) %>%
  mutate(type = ifelse(id %in% id_patient , "PATIENT", type)) %>%
  group_by(id, cat, localization, room, type) %>%
  summarise(
    sum_room = n() * 30,
    n = n(),
    .groups = 'drop'
  )

test_loc$room <- factor(test_loc$room, levels = c("Corridor", "Office", "Nursing station", "Medical Restroom", "Paramedical Restroom"))

# Boxplot & jittered points (Restroom & Corridor)
test_loc %>% filter(localization %in% c(19,20,21,22,23,24)) %>%
  ggplot( aes(x=type, y=sum_room/3600, fill=type)) +
    geom_boxplot() +
    scale_fill_viridis(discrete = TRUE, alpha=0.6) +
    geom_jitter(color="black", size=0.4, alpha=0.9) +
    ggh4x::facet_grid2(cols = vars(room), scales = "free_y", independent  ="y") +
    theme_bw() +
    theme(
      legend.position="none",
      plot.title = element_text(size=11),
      axis.text.x = element_text(angle = 35, hjust = 1)
    ) +
    #ggtitle("Cumulative time spent in restroom or corridor by category of HCW") +
    xlab("") +
    ylab("Cumulative time (h)")

# Violin plot (Restroom & Corridor)    
test_loc %>% filter(localization %in% c(19,20,21,22,23,24)) %>%
  ggplot( aes(x=type, y=sum_room/3600, fill=type)) +
    geom_violin() +
    geom_boxplot(width=.1) +
    scale_fill_viridis(discrete = TRUE, alpha=0.6) +
    geom_jitter(color="black", size=0.4, alpha=0.9) +
    ggh4x::facet_grid2(cols = vars(room), scales = "free_y", independent  ="y") +
    theme_bw() +
    theme(
      legend.position="none",
      plot.title = element_text(size=11),
      axis.text.x = element_text(angle = 35, hjust = 1)
    ) +
    #ggtitle("Cumulative time spent in restroom or corridor by category of HCW") +
    xlab("") +
    ylab("Cumulative time (h)")
    
# Violin plot (Restroom)
test_loc %>% filter(room == "Medical Restroom" | room == "Paramedical Restroom") %>%
  ggplot( aes(x=type, y=sum_room/3600, fill=type)) +
    geom_violin() +
    geom_boxplot(width=.1) +
    scale_fill_viridis(discrete = TRUE, alpha=0.6) +
    geom_jitter(color="black", size=0.4, alpha=0.9) +
    theme_bw() +
    theme(
      legend.position="none",
      plot.title = element_text(size=11),
      axis.text.x = element_text(angle = 35, hjust = 1)
    ) +
    #ggtitle("Cumulative time spent in Restrooms by category of HCW") +
    xlab("") +
    ylab("Cumulative time (h)")
```


## ORDERED CUMULATIVE TIME SPENT IN ROOMS
```{r}
pal = c("#5CD6D6", "#A9B9E8", "#FFA766", "#666699")
pal = c("#5CD6D6BF", "#A9B9E8BF", "#FFA766BF", "#666699BF") #ALPHA = 0.75
names(pal) <- c('PARAMEDICAL', 'PATIENT', 'MEDICAL', 'ROOM')


## Cumulative time in patients rooms
patients_room <- test_loc %>% filter(localization %in% id_room_patient) %>%
  group_by(id, .drop = "group") %>% 
  summarise(sum_patient = sum(sum_room)) %>%
  mutate(sum_room = sum_patient) %>%
  mutate(room = "Patients Rooms") %>% 
  left_join(test_loc %>% distinct(id, .keep_all = T) %>% select(id,type), by = join_by("id")) %>%
  select(id, sum_room, room, type)

other_room <- test_loc %>% filter(!localization %in% id_room_patient) %>% filter(!is.na(room)) %>%
  select(id, sum_room, room, type)

total_room <- bind_rows(other_room, patients_room)
total_room$room <- factor(total_room$room, levels = c("Corridor", "Patients Rooms",  "Nursing station", "Office", "Paramedical Restroom", "Medical Restroom"))

p_cumulative_loc <- total_room %>%
  ggplot( aes(x=type, y=sum_room/3600, fill=type)) +
    geom_boxplot() +
    # scale_fill_viridis(discrete = TRUE, alpha=0.6) +
    scale_fill_manual(values = pal) +
    geom_jitter(color="black", size=0.4, alpha=0.9) +
    ggh4x::facet_grid2(cols = vars(room), scales = "free_y", independent  ="y") +
    
    theme_bw() +
    theme(
      legend.position="none",
      plot.title = element_text(size=11,hjust = 0.5),
      axis.text.x = element_text(angle = 35, hjust = 1)
    ) +
    # labs(title = "Cumulative time spent in rooms") +
    labs(x = "", y = "Cumulative time (h)")
    

print(p_cumulative_loc)
ggsave(file = file.path(fig_path, paste0("cumulative-time-rooms", ".png")), plot = p_cumulative_loc, height = 5, width = 12)
```


## TEMP - Tracking individual
```{r}
paths <- do.call(rbind, global_localization) %>% filter(between(time, 600, 600+2880)) %>% ## FILTER TO KEEP ONLY THE 24H OF INTEREST
  left_join(rooms %>%
              distinct(id_room, .keep_all = T) %>%
              select(id_room,room), by = c("localization" = "id_room")) %>%
  mutate(room = ifelse(is.na(room), "-1 NOT HERE", room))


save_individual_path <- function(ind) {
  ind_cat <- ifelse(!is.na(admission[admission$id == ind, "cat"]), admission[admission$id == ind, "cat"], "patient")
  title <-paste0('Individual trajectory over time - ', ind, ' - ', ind_cat) 
  p <- ggplot(paths %>% filter(id == ind), aes(x = time * 30 + begin_date, y = room)) +
    geom_path(aes(group = id)) +  # geom_path -> connected lines
    geom_point(aes(shape = id)) +  # geom_point -> points
    labs(title = title, x = "Time", y = "Room") +
    theme_bw() +
    theme(
    plot.title = element_text(size = 25, hjust = 0.5), #
    axis.text = element_text(size = 20),
    axis.title = element_text(size = 20),
    legend.text = element_text(size = 20),
    legend.title = element_text(size = 20),
    legend.position="none") 
    
  # filename
  file_name <- file.path(ind_paths_path, paste0(ind,"_", ind_cat, "_fig-traj", ".png"))
  ggsave(file = file_name, plot = p, height = 6, width = 30)
}

#map -> apply function for each individual
invisible(map(id_interacting, save_individual_path))

```



<!-- ################################# TEMPORARY - DOUBLE/TRIPLE ROOM INFERENCE ############################## -->

## TEMP: EXTRACTING DOUBLE/TRIPLE ROOMS
```{r}
wd <- getwd()
knitr::opts_chunk$set(root.dir = wd)
data_path <- file.path(wd,"..", "..", "data")
nodscov2_path <- file.path(data_path, "data-nodscov2") 
loc_nodscov2_path <- file.path(wd, "..", "..", "out", "loc-nodscov2")
fig_path <- file.path(loc_nodscov2_path,"..","fig")
ind_paths_path <- file.path(fig_path, "individual-paths")
load(file.path(loc_nodscov2_path,"dev-localization-nodscov2.RData")) ##overwrite admission
## TRUNCATE TO KEEP ONLY 24H (24/05/06 12:00 TO 24/05/07 12:00)
end_date - begin_date ##end of last interaction
new_begin_date <- begin_date + (5*60*60) ## OFFSET TO START THE DAY AT 12AM
new_end_date <- new_begin_date + (24*60*60)
print(new_end_date - new_begin_date)
t_begin <- 5*60*2 ## OFFSET t
t_end <- (t_begin + 24*60*2) - 1




id_patient <- admission %>% filter(status == 'PA') %>% pull(id)
## IN RP ICU DURING THE STUDY -> ADDED BEDS, 2 DOUBLE ROOMS and 2 "TRIPLE ROOMS"
# equivalence id_patient <-> integer
# will give NA if not a patient -> excluded
# if < 2 patients -> will be skipped
name_to_index <- setNames(seq_along(id_patient), id_patient)

update_co_occurrence_matrix <- function(cluster, matrix, name_to_index) {
  if (length(cluster) > 1) {
    for (i in 1:(length(cluster) - 1)) {
      for (j in (i + 1):length(cluster)) {
        idx_i <- name_to_index[cluster[i]]
        idx_j <- name_to_index[cluster[j]]
        matrix[idx_i, idx_j] <- matrix[idx_i, idx_j] + 1
        matrix[idx_j, idx_i] <- matrix[idx_j, idx_i] + 1
      }
    }
  }
  return(matrix)
}

# initialization
co_occurrence_matrix <- matrix(0, nrow = length(id_patient), ncol = length(id_patient))
rownames(co_occurrence_matrix) <- id_patient
colnames(co_occurrence_matrix) <- id_patient

## for each time step -> count
for (t in clusters[(u <- seq_along(clusters)) %in% t_begin:(t_end)]) {
  for (cluster in t) {
    co_occurrence_matrix <- update_co_occurrence_matrix(cluster, co_occurrence_matrix, name_to_index)
  }
}
total_occurrences <- colSums(co_occurrence_matrix)

## Adjacency graph
graph <- graph.adjacency(co_occurrence_matrix,
                         weighted=T,
                         mode="undirected",
                         diag=FALSE)

plot.igraph(graph,
            vertex.label=V(graph)$name,
            #edge.width=log10(E(graph)$weight),
            edge.label=E(graph)$weight,
            edge.label.cex=0.8,
            vertex.size=5,
            vertex.label.cex=0.8,
            layout=layout_with_kk) 

tkplot(graph,
          vertex.label=V(graph)$name,
            #edge.width=log10(E(graph)$weight),
            edge.label=E(graph)$weight,
            edge.label.cex=0.8,
            vertex.size=5,
            vertex.label.cex=0.8,
            layout=layout_with_kk)
```



```{r}
## MATRIX TO DF (filtering to remove duplicates, matrix is symmetrical..., and order it by highest count)
co_occurrence_df <- as.data.frame(as.table(co_occurrence_matrix))
co_occurrence_df <- co_occurrence_df[co_occurrence_df$Var1 != co_occurrence_df$Var2, ]
co_occurrence_df <- co_occurrence_df[!duplicated(t(apply(co_occurrence_df, 1, sort))), ]
co_occurrence_df <- co_occurrence_df[order(-co_occurrence_df$Freq), ]


## function to find double room
find_double_rooms <- function(df, n_double) {
  selected_clusters <- character()
  double_rooms <- list()

  # Select double rooms
  for (i in 1:n_double) {
    pair <- df[!df$Var1 %in% selected_clusters & !df$Var2 %in% selected_clusters, ][1, ]
    if (nrow(pair) > 0) {
      double_rooms[[i]] <- c(as.character(pair$Var1), as.character(pair$Var2))
      selected_clusters <- c(selected_clusters, as.character(pair$Var1), as.character(pair$Var2))
    }
  }

  return(double_rooms)
}

double_rooms <- find_double_rooms(co_occurrence_df, n_double = 2)
print(double_rooms)
```


## TRIPLE ROOMS (NOT WORKING ATM)
```{r}
# library(gtools)
# triplets <- as.data.frame(combinations(n = 18, r = 3, v = id_patient)) %>% mutate(Freq = 0)
# 
# ## Freq each triplet in a cluster
# for (t in clusters) {
#   for (cluster in t) {
#     if (length(cluster) > 2){
#       for (j in 1:nrow(triplets)) {
#         triplet <- triplets[j, ]
#         if (all(triplet %in% cluster)) {
#           triplets[j,]$Freq <- triplets[j,]$Freq + 1
#         }
#       }
#     }
#   }
# }
```

<!-- ################################# GARBAGE ############################## -->

```{r}
# ## check which indivuals have > 3 "shifts"
# sup_3_shifts <- shifts %>% 
#   group_by(individual) %>% 
#   summarise(n_shifts = n()) %>% 
#   filter(n_shifts > 3) %>%
#   left_join(admission %>% select(id,cat), by = c("individual" = "id")) %>%
#   select(individual, cat, n_shifts)
```

## SHIFTS VS INTERACTION
```{r}
# df_long <- data %>%
#   mutate(date_posix_end = date_posix_first + length) %>% 
#   pivot_longer(cols = c(from, to), names_to = "direction", values_to = "individual") %>%
#   arrange(individual, date_posix_first)
# 
# calculate_actual_interaction_time <- function(df) {
#   if(nrow(df) == 0) return(0)
#   
#   df <- df %>% arrange(date_posix_first)
#   total_time <- 0
#   current_start <- df$date_posix_first[1]
#   current_end <- df$date_posix_end[1]
#   
#   for(i in 2:nrow(df)) {
#     if(df$date_posix_first[i] <= current_end) {
#       current_end <- max(current_end, df$date_posix_end[i])
#     } else {
#       total_time <- total_time + as.numeric(difftime(current_end, current_start, units = "hours"))
#       current_start <- df$date_posix_first[i]
#       current_end <- df$date_posix_end[i]
#     }
#   }
#   total_time <- total_time + as.numeric(difftime(current_end, current_start, units = "hours"))
#   return(total_time)
# }
# 
# len_int <- df_long %>%
#   group_by(individual) %>%
#   summarise(total_int = calculate_actual_interaction_time(cur_data()))
# 
# len_shifts <- shifts %>%
#   group_by(individual) %>%
#   summarise(total_shift = sum(shift_length))
# 
# len_tot <- left_join(len_shifts, len_int, by = join_by(individual))  %>%
#   mutate(len_diff = total_shift - total_int) %>%
#   left_join(admission %>% select(id,cat), by = c("individual" = "id"))
# 
# 
# len_tot %>% filter(total_int > total_shift) 
```