---
title: "dev-test-launch"
author: "Olivier GAUFRÈS"
date: "2024-07-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(Rcpp)
```


```{r}
wd <- getwd()
knitr::opts_chunk$set(root.dir = wd)
args = commandArgs(trailingOnly=TRUE)

sim_nodscov2_path <- file.path(wd, "..", "..", "out", "sim-nodscov2")
set.seed(123)
```

```{r}
###### launch_sensibility.R (CLUSTER)
load(file.path(wd, '..', '..', 'out', 'sensibility-analysis', 'sim-beta-10.0' ,'parameters-model-beta-10.0.RData'))
cpp_path <- file.path(wd,'..','..','cpp', 'nodscov2', 'dev-model-nodscov2.cpp')
sourceCpp(cpp_path)
```

## global_data
```{r}
global_data <- lapply(1:length(truncated_localization), function(t){
  df <- data.frame(id = truncated_localization[[t]]$id,
                   info = admission_sim$info,
                   #room = admission_sim$room,
                   #interacting = ifelse(id %in% truncated_interaction$from | id %in% truncated_interaction$to, T, F)
                   localization_ti = truncated_localization[[t]]$localization,
                   lambda_c = 0,
                   lambda_e = 0
                   )
  df <- df %>% filter(localization_ti != -1)
  return(df)
})
```



```{r}
## CREATE ENDLESS DAY OBJECTS
test_interaction <- rep(truncated_interaction, n_days)
test_data <- rep(global_data, n_days)
test_environment <- rep(truncated_environment, n_days)
test_status <- truncated_status
new_n_subdivisions <- (t_end-t_begin +1)*n_days
```

```{r}
## RANDOM INDEX CASE
print('sampling a random index case')
#id_index <- sample(x= admission_sim %>% distinct(id) %>% pull(), size = 1)
id_index <- "001-0038-B-S"
print(id_index)
# Update global status
print('updating global status')
test_status <- test_status %>%
  mutate(t_inf = ifelse(id == id_index,
                        as.integer(1),
                        t_inf),
         t_incub = ifelse(id == id_index,
                          as.integer(t_inf + runif(1, min = 2880*1, max = 2880*5)),
                          t_recover),
         t_recover = ifelse(id == id_index,
                            as.integer(t_incub + runif(1, min = 2880*3, max = 2880*7)),
                            t_recover),
         inf_by = ifelse(id == id_index,
                         "INDEX",
                         inf_by))

```

```{r}
t = 23914
id = id_index
tau = 60 * 60 * 24
dt = 30
deltat = dt/(tau)

status_ti_j <- Get_status_j(
  id = id_index,
  global_status = test_status,
  t = t
)

status_ti <- Get_status_t(
  global_status = test_status,
  ids = test_data[[t]]$id,
  t = t
)

status_tim1 <- Get_status_t(
  global_status = test_status,
  ids = test_data[[t]]$id,
  t = t - 1
)

list_encountered <- List_encountered(
  id = id_index,
  interaction_ti = test_interaction[[t]]
)

list_inf_encountered <- List_inf_encountered(
  id = id_index,
  interaction_ti =  test_interaction[[t]],
  global_status = test_status,
  t = t
)

lambda_c <- Lambda_c(
  ids_ti = test_data[[100000]]$id,
  interaction_ti = test_interaction[[100000]],
  status_ti = status_ti,
  beta = beta,
  deltat = deltat
)

lambda_e <- Lambda_e(
  info_ti = test_data[[t]]$info,
  localization_ti = test_data[[t]]$localization_ti,
  environment_ti = test_environment[[t]] %>% mutate(env = 40),
  B = B,
  env_threshold = 0,
  deltat = deltat
)
```


```{r}
Update_environment(
  ids_ti = test_data[[1]]$id,
  info_ti = test_data[[1]]$info,
  environment_tim1 = test_environment[[1]],
  localization_ti = test_data[[1]]$localization_ti,
  status_tim1 = status_tim1,
  mu = mu,
  nu = nu,
  deltat = deltat,
  t = t
)
```





```{r}
beta = 0.79
ta <- Sys.time()
result <- simulation(global_interaction = test_interaction,
                     global_environment = test_environment,
                     global_data = test_data,
                     global_status = test_status,
                     admission = admission_sim,
                     beta = beta,
                     B = B,
                     nu = nu,
                     mu = mu,
                     env_threshold = env_threshold,
                     dt = dt)
tb <- Sys.time()
print(tb - ta)

```


```{r}
id_sim <- ifelse(length(args)==0, "dev-test-endless-day", args[1])
id_sim_path <- file.path(sim_nodscov2_path, id_sim)

if (!dir.exists(id_sim_path)) {
  dir.create(id_sim_path, recursive = TRUE)
}


save(truncated_interaction,
     truncated_localization,
     truncated_environment,
     admission_sim,
     beta,
     nu,
     mu,
     B,
     env_threshold,
     dt,
     new_n_subdivisions,
     n_days,
     t_begin,
     t_end,
     result,
     file = file.path(id_sim_path, paste0(id_sim, "-", "dev-cpp-dev-simulation-nodscov2.RData"))
     )
```





