---
title: "Interaction-nodscov2"
author: "Olivier GAUFRÈS"
date: "2024-05-03"
output: html_document
---

## Libraries
```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(lubridate)
library(tidyr)
library(viridis)
```

## Working directory & paths
```{r wd and paths}
wd <- getwd()
knitr::opts_chunk$set(root.dir = wd)

data_path <- file.path(wd,"..", "..", "data")
observed_path <- file.path(data_path,"data-observed")
synthetic_path <- file.path(data_path, "data-synthetic-graphs")
simplified_path <- file.path(data_path, "data-simplified")
expanded_path <- file.path(data_path,"data-expanded")
nodscov2_path <- file.path(data_path, "data-nodscov2") 
```


## NodsCov2 data (not shared)
```{r}
# load("Y:/ogaufres/pacri-non-sync/data/data-nodscov2/admission_ctc_nodscov2.RData")
# load("Y:/ogaufres/pacri-non-sync/data/data-nodscov2/list_ward.RData")

load(file.path(nodscov2_path, "admission_ctc_nodscov2.RData"))
load(file.path(nodscov2_path, "list_ward.RData"))
```

## FIXING ENCODING
```{r}
Encoding(admission$hospital) <- 'latin1'
```

## Data structure
```{r}
### ADMISSION = Individual's info
head(admission)
admission %>% distinct(hospital)

### LIST_WARD = LIST OF DATAFRAMES, EACH DF CONTAINS WARDS' INTERACTIONS
# Wards names
names(list_ward)
# Structures of wards df
head(list_ward$`Raymond_Poincare-Reanimation-20200506-20200507`)
```


## Individual proportions
```{r}
head(admission)

## Patients / HCW in all wards/hospitals
table(admission$status)

## Patients / HCW by cat (NA == patients)
table(admission$status, admission$cat, useNA = "always") 

## Proportion of individuals/ward etc..
table(admission$hospital, admission$ward)
```


## "FILTRATION"
```{r}
head(admission %>% filter(ward == "Reanimation"))

## Ind in each reanimation ward
head(admission %>% filter(ward == "Reanimation") %>% group_by(hospital) %>% summarise( n = n(), .groups = "drop"))

## Cat in each reanimation ward
head(admission %>% filter(ward == "Reanimation") %>% group_by(hospital, cat) %>% summarise( n = n(), .groups = "drop"))
```


## PLOTS
```{r}
## Reanimation wards
admission %>%
  filter(ward == "Reanimation" ) %>%
  filter(hospital != "APHP - NECKER ENFANTS MALADES") %>%
  mutate(cat = ifelse(is.na(cat), "Patients", cat)) %>%
  group_by(hospital, cat) %>%
  summarise( n = n(), .groups = "drop") %>%
    ggplot(., aes(x = cat, y = n)) +
    geom_bar(stat = "identity") +
    facet_grid(cols = vars(hospital)) +
    theme_bw() +
    theme(axis.text.x = element_text(angle = 35, hjust = 1)) +
  labs(x = "Categories", y = "Number of individuals")

## ReaChirurgie wards (For HC LYON EDOUARD HERRIOT 's REACHIRURGIE WARD)
admission %>%
  filter(ward == "ReaChirurgie") %>%
  mutate(cat = ifelse(is.na(cat), "Patients", cat)) %>%
  group_by(hospital, cat) %>%
  summarise( n = n(), .groups = "drop") %>%
    ggplot(., aes(x = cat, y = n)) +
    geom_bar(stat = "identity") +
    facet_grid(cols = vars(hospital)) +
    theme_bw() +
    theme(axis.text.x = element_text(angle = 35, hjust = 1))


```


## DF of interest
```{r}
## We keep wards with the lowest number of visitors (hyp. no visitors)
keep_names <- c("Raymond_Poincare-Reanimation-20200506-20200507",
          "Edouard_Herriot-Reanimation-20200609-20200610")

list_rea <- list_ward[keep_names]
```


## MODIFY INDIVIDUAL IDS (include PA/PE in id)
```{r}
## (TEMPORARY)
admission_rea <- admission %>%
  filter(ward == "Reanimation") %>% 
  filter(hospital != "APHP - NECKER ENFANTS MALADES")

table(admission_rea$hospital, admission_rea$cat)
rm(admission_rea)
## END (TEMPORARY)



## FILTER ADMISSION
admission_keep <- admission %>%
  ## Remove visitors/admin/logistics/investigators
  filter(ward == "Reanimation") %>% 
  filter(hospital != "APHP - NECKER ENFANTS MALADES") %>%
  filter(!(cat %in% c("administration",
                  "investigation",
                  "logistic",
                  "visitor"))) %>%
  ## ADD PE/PA IN ADMISSION'S IDs (id)
  mutate(id_bis = paste0(status,"-",id))


list_rea <- list_ward[keep_names]
## FILTER THE DATAFRAMES
list_rea <- lapply(list_rea, function(x) {
  ## FILTER INTERACTIONS TO KEEP ONLY HCW AND PATIENTS
  x <- x%>% filter(from %in% admission_keep$id & to %in% admission_keep$id)
  ## ADD INFO OF THE STATUS FOR INDIVIDUALS
  x <- left_join(x, admission_keep %>% select(id, status), by = c("from" = "id")) %>%
    rename(from_status = status) %>%
    left_join(admission_keep %>% select(id, status), by = c("to" = "id")) %>%
    rename(to_status = status)
})
```


## DISTRIBUTIONS
```{r}
poincare <- "Raymond_Poincare-Reanimation-20200506-20200507"
herriot <- "Edouard_Herriot-Reanimation-20200609-20200610"


data_rea <- bind_rows(
  mutate(list_rea[[poincare]], hospital = "Raymond Poicaré"),
  mutate(list_rea[[herriot]], hospital = "Edouard Herriot") ) %>%
  mutate(type_int = paste0(from_status, "-", to_status)) %>%
  mutate(type_int = ifelse(type_int == "PA-PE", "PE-PA", type_int))


## n / type of int
data_rea %>%
  group_by(hospital, type_int) %>%
  summarise(n = n(), .groups = "drop") %>%
  ggplot(aes(x = type_int, y = n)) +
  geom_bar(stat = "identity") +
  facet_grid(cols = vars(hospital)) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 35, hjust = 1)) +
  labs(title = "Number of interaction over time")

# n distribution / hour
data_rea %>%
  group_by(hospital, hour(date_posix_first), type_int) %>%
  summarise(n = n(), .groups = "drop") %>%
  mutate(hour = `hour(date_posix_first)`) %>%
  ggplot(aes(x = hour, y = n)) +
  geom_bar(stat = "identity") +
  facet_grid(cols = vars(type_int), rows = vars(hospital)) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 35, hjust = 1)) +
  labs(title = "Number of interaction over time") +
  labs(x = "Hour of the day", y = "Number of interactions")
```


## Cumulative time spent with patients by category of HCW
```{r}
length_cat <- list_rea[[poincare]] %>%
  filter((from_status == "PA" & to_status == "PE") | (from_status == "PE" & to_status == "PA")) %>%
  mutate(id_pe = ifelse(from_status == "PE", from, to)) %>%
  left_join(admission %>% select(id, cat), by = c("id_pe" = "id"))


sum_length_cat <- length_cat %>%
  group_by(id_pe, cat) %>%
  summarise(
    sum_cat = sum(length),
    n_cat = n(),
    adj_sum_cat = sum_cat / n_cat,
    .groups = 'drop'
  )

# Boxplot & jittered points
sum_length_cat %>%
  ggplot( aes(x=cat, y=sum_cat/3600, fill=cat)) +
    geom_boxplot() +
    scale_fill_viridis(discrete = TRUE, alpha=0.6) +
    geom_jitter(color="black", size=0.4, alpha=0.9) +
    theme_bw() +
    theme(
      legend.position="none",
      plot.title = element_text(size=11),
      axis.text.x = element_text(angle = 35, hjust = 1)
    ) +
    ggtitle("Cumulative time spent interacting with patient by category of HCW") +
    xlab("") +
    ylab("Cumulative time interacting (h)")

# Violin plot
sum_length_cat %>%
  ggplot( aes(x=cat, y=sum_cat/3600, fill=cat)) +
    geom_violin() +
    scale_fill_viridis(discrete = TRUE, alpha=0.6) +
    geom_jitter(color="black", size=0.4, alpha=0.9) +
    theme_bw() +
    theme(
      legend.position="none",
      plot.title = element_text(size=11),
      axis.text.x = element_text(angle = 35, hjust = 1)
    ) +
    ggtitle("Cumulative time spent interacting with patient by category of HCW") +
    xlab("") +
    ylab("Cumulative time interacting (h)")

```



## PA-PA INTERACTIONS
```{r}
k_RP <- list_rea[[poincare]] #%>% filter(length > 300)
k_EH <- list_rea[[herriot]] #%>% filter(length > 300)

table(k_RP$from_status, k_RP$to_status)
k_RP %>% filter(from_status == "PA" & to_status == "PA")
k_RP %>% filter(from_status == "PA" & to_status == "PA") %>% group_by(from,to) %>% summarise(len = sum(length))

table(k_EH$from_status, k_EH$to_status)
k_EH %>% filter(from_status == "PA" & to_status == "PA")
k_EH %>% filter(from_status == "PA" & to_status == "PA") %>% group_by(from) %>% summarise(len = sum(length))
```

## Raymond Poincaré double rooms hypothesis
```{r}
### HYP : "001-0038-B-S" and "001-0039-B-F" are in the same room
## ORDER FROM/TO
temp_a <- list_rea[[poincare]] %>%
  filter(from %in% c("001-0038-B-S", "001-0039-B-F") 
         | to %in% c("001-0038-B-S", "001-0039-B-F")) %>%
  filter(!(from_status == "PA" & to_status == "PA")) %>%
  mutate(n_from = ifelse((from == "001-0038-B-S" | from == "001-0039-B-F"), from, to  )
         , n_to = ifelse((to == "001-0038-B-S" | to == "001-0039-B-F"), from, to))


pe_a <- unique(c(temp_a$to[temp_a$to_status == "PE"]))
overlap_a <- data.frame()

for (individual in pe_a) {
  # Filter to keep only HCW's interaction
  interactions <- temp_a %>%
    filter(n_to == individual)
  
  # If the HCW interacts with both patients
  if (nrow(interactions) >= 2) {
    # double for loop to check if i and [j=i+1;n] are overlapping] for i 1:nrow(interaction)
    for (i in 1:(nrow(interactions)-1)) {
      for (j in (i+1):nrow(interactions)) {
        # Check if overlapping
        if (interactions$date_posix_first[i] <= (interactions$date_posix_first[j] + interactions$length[j]) &&
            (interactions$date_posix_first[i] + interactions$length[i]) >= interactions$date_posix_first[j]) {
          if (interactions$n_from[i] != interactions$n_from[j]){
          overlap_a <- bind_rows(overlap_a, interactions[c(i, j), ]) 
          }
        }
      }
    }
  }
}
rm(pe_a)
rm(interactions)
rm(temp_a)

summary(overlap_a)
```


```{r}
### HYP : "001-0127-B-A" and "001-0128-Z-K" are in the same room

temp_b <- list_rea[[poincare]] %>%
  filter(from %in% c("001-0127-B-A", "001-0128-Z-K" ) 
         | to %in% c("001-0127-B-A", "001-0128-Z-K" )) %>%
  filter(!(from_status == "PA" & to_status == "PA")) %>%
  mutate(n_from = ifelse((from == "001-0127-B-A" | from == "001-0128-Z-K"), from, to  )
         , n_to = ifelse((to == "001-0127-B-A" | to == "001-0128-Z-K"), from, to))


pe_b <- unique(c(temp_b$to[temp_b$to_status == "PE"]))
overlap_b <- data.frame()

for (individual in pe_b) {
  # Filter to keep only HCW's interaction
  interactions <- temp_b %>%
    filter(n_to == individual)
  
  # If the HCW interacts with both patients
  if (nrow(interactions) >= 2) {
    # double for loop to check if i and [j=i+1;n] are overlapping] for i 1:nrow(interaction)
    for (i in 1:(nrow(interactions)-1)) {
      for (j in (i+1):nrow(interactions)) {
        # Check if overlapping
        if (interactions$date_posix_first[i] <= (interactions$date_posix_first[j] + interactions$length[j]) &&
            (interactions$date_posix_first[i] + interactions$length[i]) >= interactions$date_posix_first[j]) {
          if (interactions$n_from[i] != interactions$n_from[j]){
          overlap_b <- bind_rows(overlap_b, interactions[c(i, j), ]) 
          }
        }
      }
    }
  }
}
rm(pe_b)
rm(interactions)
rm(temp_b)

summary(overlap_b)
```
<!-- ################################# GARBAGE ############################## -->

