---
title: 'intervention-analysis'
author: 'Olivier GAUFRÈS'
date: '2024-07-30'
output: html_document
---

```{r}
## LIBRARIES
library(ggplot2)
library(dplyr)
library(tidyr)
library(purrr)
library(data.table)
```


```{r}
##PATHS
wd <- getwd()

source(file.path(wd, 'intervention-analysis_fun.R'))
out_path <- file.path(wd,'..','..', 'out')
loc_path <- file.path(out_path,'loc-nodscov2')
intervention_path <- file.path(out_path, 'intervention-analysis')
```


```{r}
archive_path <- file.path(intervention_path, 'out-01-08-24.tar.gz')
archive_path <- file.path(intervention_path, 'out-01-08-24-bis.tar.gz')
content <- untar(archive_path, list = TRUE)

# # TEMP LOAD WITHOUT EXTRACT
# temp_dir <- tempdir()
# temp_file <- file.path(temp_dir, "temp.RData")
# archive::archive_extract(archive_path, files = "out/sim_1-4_0/results/sim_1-4_0_68.RData", dir = temp_file)
# load(file.path(temp_file, "out/sim_1-4_0/results/sim_1-4_0_68.RData"))

```

## LOAD LOCALIZATION DATA & GLOBAL PARAMETERS
```{r}
load(file.path(loc_path, 'dev-localization-nodscov2.RData'))
load(file.path(intervention_path, "parameters-admission-nodscov2.RData"))

##TO FIX IN loc-to-RData (rerun to update parameters.RData)
admission <- admission %>% filter(id %in% admission_sim$id)
```

## ADJUST THE BEGIN/END DATES OF SIMULATIONS
```{r}
new_begin_date <- begin_date + t_begin*30 ## OFFSET TO START THE DAY AT 12AM
new_end_date <- new_begin_date + new_n_subdivisions*30
print(new_end_date - new_begin_date)
```
## BETA/NU COUPLES -> READ SIMULATION RESULTS
```{r}
#read_all_files <- function(path, )

## ALL COUPLES INSIDE A LIST, EVERY SIMULATION INSIDE SUB-LIST NAMED sim<beta>_<nu> --> WILL BE NAMED A COUPLE
list_dirs <- list.dirs(path = file.path(intervention_path, 'out'), recursive = F, full.names = F)
list_sim <- list()

## READ ALL SIMULATION FOR ALL AVAILABLE COUPLES
for (dir in list_dirs){
  list_sim[[dir]] <- list()
  sim_path <- file.path(intervention_path, 'out', dir, 'results')
  rdata_files <- list.files(sim_path, pattern = "^sim_.*\\.RData$", full.names = F)
  invisible(lapply(rdata_files, function(file) load_rdata_to_list(file, list_sim, dir)))
}
```

## FOR EACH SIMULATION -> COMPUTE SAR
```{r}
## CATEGORY GROUPING INTO TYPE
cat_paramedical <- c("nurse", "student nurse", "aux nurse")
cat_medical <- c("physician", "ext physician", "reeducation staff", "other")

## IDS BY CATEGORY
id_patient <- admission_sim %>% filter(info == 0) %>% distinct(id) %>% pull()
id_hcw <- admission_sim %>% filter(info == 1) %>% distinct(id) %>% pull()
## FOR MEDICAL/PARAMEDICAL WE USE ADMISSION (INDIVIDUALS BEFORE ADDING NEW PATIENTS)
id_paramedical <- admission %>% filter(cat %in% cat_paramedical) %>% distinct(id) %>% pull()
id_medical <- admission %>% filter(cat %in% cat_medical) %>% distinct(id) %>% pull()

## GET SARs FOR ALL COUPLES
list_SAR <- get_all_SAR(list_sim = list_sim, 
                        id_patient = id_patient, 
                        id_hcw = id_hcw, 
                        id_paramedical = id_paramedical, 
                        id_medical = id_medical)

```

## SAR METRICS
```{r}
all_SAR_g_metrics <- get_all_SAR_g_metrics(list_SAR = list_SAR)

##SELECT COUPLES FOR SAR +/- 20%

all_SAR_g_metrics %>% filter(dplyr::between(SAR_median, 0.10, 0.30))
all_SAR_g_metrics %>% filter(dplyr::between(SAR_mean, 0.10, 0.30)) %>% select(beta, nu , SAR_mean, SAR_median, SAR_sd)

all_SAR_metrics <- compute_all_SAR_metrics(list_SAR = list_SAR)
```

## SAR_distribution  
```{r}
get_SAR_distribution <- function(couple, list_SAR){
  SAR_distrib <- rbindlist(list_SAR[[couple]], idcol = 'id_sim')  %>% group_by(id_sim)
  return(SAR_distrib)
}
get_SAR_distribution(couple, list_SAR)
```

## EPIDEMIC DURATION
```{r}
list_epidemic_duration <- get_all_epidemic_duration(list_sim = list_sim)
all_epidemic_duration_metrics <- get_all_epidemic_duration_metrics(list_epidemic_duration = list_epidemic_duration)
```

## MAX N INFECTIOUS AT PEAK




## ALL METRICS IN ONE DF
```{r}
all_metrics <- left_join(all_SAR_metrics, all_epidemic_duration_metrics, by="couple", suffix=c("",".y")) %>%
  select(-ends_with(".y"))

write.csv2(all_metrics, file = file.path(intervention_path, 'intervention-all_metrics.csv'), row.names = F)

```




#### WHEN COUPLES ARE SELECTED
```{r}
all_metrics <- read.csv2(file = file.path(intervention_path, 'intervention-all_metrics.csv'))
couple_same_SAR <- all_metrics %>% filter(dplyr::between(SAR_median, 0.20, 0.30)) %>% pull(couple)


### READ ONLY RDATA FOR SELECTED BETA/NU COUPLES
list_sim <- list()
for (couple in couple_same_SAR){
  list_sim[[couple]] <- list()
  sim_path <- file.path(intervention_path, 'out', couple, 'results')
  rdata_files <- list.files(sim_path, pattern = "^sim_.*\\.RData$", full.names = F)
  invisible(lapply(rdata_files, function(file) load_rdata_to_list(file, list_sim, couple)))
}

## COMPUTE ALL THE SAR FOR EACH COUPE/SIMULATION
list_SAR <- get_all_SAR(list_sim = list_sim, 
                        id_patient = id_patient, 
                        id_hcw = id_hcw, 
                        id_paramedical = id_paramedical, 
                        id_medical = id_medical)

list_epidemic_duration <- get_all_epidemic_duration(list_sim = list_sim)
all_epidemic_duration_metrics <- get_all_epidemic_duration_metrics(list_epidemic_duration = list_epidemic_duration)

## CONCATENATE THE NSIMULATION DATAFRAMES  FOR 1 COUPLE TO 1 DATAFRAME FOR 1 COUPLE
list_df <- list()
for(couple in couple_same_SAR){
  list_df[[couple]] <- rbindlist(list_SAR[[couple]], idcol = 'id_sim') %>% mutate(couple = couple)
}

df_SAR <- rbindlist(list_df) 
n_ext <- df_SAR %>% group_by(couple) %>% filter(Global == 0) %>% summarise(n = n())


df_SAR_long <- df_SAR %>%
    pivot_longer(cols = c("Global", "HCW", "Patient", "Paramedical", "Medical", "Environment", "Contact" , 
                           "Patient_Contact", "Patient_Environment", "Paramedical_Contact", "Paramedical_Environment",
                          "Medical_Contact", "Medical_Environment"), names_to = "Type_SAR", values_to = "SAR")
df_SAR_long$Type_SAR <- factor(df_SAR_long$Type_SAR, levels = c("Global", "HCW", "Patient", "Paramedical", "Medical", "Environment", "Contact",  "Patient_Contact", "Patient_Environment", "Paramedical_Contact", "Paramedical_Environment", "Medical_Contact", "Medical_Environment"))

selected_couples <- c(paste(rep('sim', 5), c('1-4_20', '1-2_16', '3-4_12', '1_8', '3-2_5'), sep = '_'))
selected_df <-  df_SAR_long %>% filter(couple %in% selected_couples) 
selected_df$couple <- factor(selected_df$couple, levels = selected_couples)
```

```{r}
## t TEST

for (id_couple in selected_couples){
  print(id_couple)
  
  print(t.test(x = df_SAR %>% filter(couple == id_couple) %>% pull(Contact),
         y = df_SAR %>% filter(couple == id_couple) %>% pull(Environment),
         paired = T))
  
  print(wilcox.test(x = df_SAR %>% filter(couple == id_couple) %>% pull(Contact),
         y = df_SAR %>% filter(couple == id_couple) %>% pull(Environment),
         paired = T))
  
}


print(wilcox.test(x = df_SAR %>% filter(couple == id_couple) %>% pull(Contact),
         y = df_SAR %>% filter(couple == id_couple) %>% pull(Global) - df_SAR %>% filter(couple == id_couple) %>% pull(Contact),
         paired = T))
```



```{r}
df_SAR_long %>%
  ggplot( aes(x=couple, y=SAR, fill=couple)) +
    geom_boxplot() +
    geom_jitter(color="black", size=0.4, alpha=0.9) +
    ggh4x::facet_grid2(cols = vars(Type_SAR), scales = "free_y", independent  ="y") +
    theme_bw() +
    theme(
      legend.position="none",
      plot.title = element_text(size=11),
      axis.text.x = element_text(angle = 35, hjust = 1)
    )
  


 p <- selected_df %>%
  ggplot( aes(x=couple, y=SAR, fill=couple)) +
    geom_boxplot() +
    geom_jitter(color="black", size=0.4, alpha=0.9) +
    ggh4x::facet_grid2(cols = vars(Type_SAR), scales = "free_y", independent  ="y") +
    theme_bw() +
    theme(
      legend.position="none",
      plot.title = element_text(size=11),
      axis.text.x = element_text(angle = 35, hjust = 1)
    )

print(p)
```


```{r}
library(ggpubr)
pal = c('Medical' = "#5CD6D6", 'Paramedical' = "#A9B9E8", 'Patient' = "#FFA766", 'Room' = "#666699")
p1 = selected_df %>%
  filter(Type_SAR %in% c("Contact", "Environment")) %>%
  ggplot( aes(x=couple, y=SAR, col = Type_SAR)) +
    geom_boxplot(position = position_dodge(width = 0.8), width = 0.5) +
    geom_jitter(size=0.4, alpha=0.9, position = position_jitterdodge()) +
    scale_color_manual(values = c("Contact" = "darkorange", "Environment" = "orchid")) +
    theme_bw() +
    theme(
      plot.title = element_text(size=11),
      axis.text.x = element_text(angle = 35, hjust = 1)
    ) + 
  labs(x = "", col = "")


p2 = selected_df %>%
  filter(Type_SAR %in% c("Patient", "Paramedical", "Medical")) %>%
  mutate(Type_SAR = factor(Type_SAR, c("Paramedical", "Medical", "Patient"))) %>%
  ggplot( aes(x=couple, y=SAR, col = Type_SAR)) +
    geom_boxplot(position = position_dodge(width = 0.8), width = 0.5) +
    geom_jitter(size=0.4, alpha=0.9, position = position_jitterdodge()) +
    scale_color_manual(values = pal[1:3]) +
    theme_bw() +
    theme(
      plot.title = element_text(size=11),
      axis.text.x = element_text(angle = 35, hjust = 1)
    ) + 
  labs(x = "", col = "") 


p3 = selected_df %>%
  filter(Type_SAR %in% c("Patient", "Paramedical", "Medical")) %>%
  pivot_wider(names_from = Type_SAR, values_from = SAR) %>%
  mutate(
    Patient = Patient * length(id_patient),
    Paramedical = Paramedical * length(id_paramedical), 
    Medical = Medical * length(id_medical)
  ) %>%
  pivot_longer(cols =  c(Patient, Paramedical, Medical), names_to = "Type_SAR", values_to = 'n') %>%
  group_by(couple, Type_SAR) %>%
  summarise(n = mean(n), .groups = "drop") %>%
  group_by(couple) %>%
  mutate(n = n/sum(n)) %>%
  ungroup() %>%
  ggplot(., aes(x = couple, y = n, fill = Type_SAR)) +
  geom_bar(stat = "identity", position = "fill") +
  theme_bw() +
  scale_fill_manual(values = pal[1:3]) +
  labs(x  = "", y = "Proportion of infected\nindividuals by type", fill = "")


p4 = selected_df %>%
  filter(grepl("_", Type_SAR)) %>% # Pour avoir uniquement les SAR contact + environment pour chaque type d'individu
  mutate(
    n = case_when(
      grepl("Patient", Type_SAR) ~ SAR * length(id_patient),
      grepl("Paramedical", Type_SAR) ~ SAR * length(id_paramedical),
      grepl("Medical", Type_SAR) ~ SAR * length(id_medical)
    ),
    ind_type = gsub("_.*$", "", Type_SAR),
    source_inf = gsub("^.*_", "", Type_SAR)
  ) %>%
  group_by(couple, Type_SAR, ind_type, source_inf) %>%
  summarise(n = mean(n), .groups = "drop") %>%
  group_by(couple, ind_type) %>%
  mutate(n = n/sum(n)) %>%
  ungroup() %>%
  ggplot(., aes(x = couple, y = n, fill = source_inf)) +
  geom_bar(stat = "identity", position = "fill") +
  facet_grid(cols = vars(ind_type)) +
  theme_bw() +
  theme(axis.text.x = element_text(hjust = 1, angle = 30)) +
  labs(x  = "", y = "Contribution of modes of transmission", fill = "")


ggarrange(p1, p2, p3, p4, labels = c("A", "B", "C", "D"), nrow = 2, ncol = 2, align = "hv")

?t.test

all_SAR_metrics <- compute_all_SAR_metrics(list_SAR = list_SAR)
```
```{r}
list_gs_df <- list()
for(couple in selected_couples){
  list_gs_df[[couple]] <- rbindlist(list_sim[[couple]], idcol = 'id_sim') %>% mutate(couple = couple)
}

df_status <- rbindlist(list_gs_df) 
test = df_status %>%
  filter(t_inf > 0) %>%
  mutate(
    source = gsub("-.*$", "", inf_by),
    type_ind = case_when(
      id %in% id_patient ~ "Patient",
      id %in% id_paramedical ~ "Paramedical",
      id %in% id_medical ~ "Medical"
    ),
    # start_exposed = as.Date(new_begin_date + t_inf * 30), 
    # end_exposed = as.Date(new_begin_date + (t_inf + t_incub) * 30)#,
    start_infected = as.Date(new_begin_date + (t_inf + t_incub) * 30),
    end_infected = as.Date(new_begin_date + (t_inf + t_incub + t_recover) * 30)
  ) %>%
  dplyr::select(couple, id_sim, id, type_ind, matches("start_|end_")) %>%
  group_by(couple, id_sim, id, type_ind) %>% 
  reframe(date = seq(start_infected, end_infected, by="1 day")) %>%
  group_by(couple, id_sim, date, type_ind) %>%
  summarise(n = n(), .groups = "drop") %>%
  complete(couple, id_sim, date, type_ind, fill = list(n = 0))
  

test_mean = test %>% 
  group_by(couple, date, type_ind) %>%
  summarise(n = mean(n), .groups = "drop") %>%
  mutate(id_sim = NA)

test %>%
  ggplot(., aes(x = date, y = n, group = id_sim)) +
  geom_line(linewidth = 0.1, col = "gray80") +
  geom_line(data = test_mean, col = "red") +
  facet_grid(cols = vars(couple), rows = vars(type_ind)) +
  theme_bw()

```




```{r}
### x = beta < 4
ggplot(all_metrics %>% filter(beta < 4), aes(x = beta, y = SAR_median, color = as.factor(nu), group = nu)) +
  geom_line() +
  geom_point() +
  geom_hline(yintercept = 0.2, linetype = "dashed", color = "darkgrey") +
  annotate("rect", xmin = -Inf, xmax = Inf, ymin = 0.2, ymax = 0.3, alpha = 0.3, fill = "lightgrey") +
  geom_hline(yintercept = 0.3, linetype = "dashed", color = "darkgrey") +
  labs(title = 'SAR Median vs Beta for Different Nu Values',
       x = 'Beta',
       y = 'SAR Median',
       color = 'Nu') +
  theme_minimal()


### x = nu
ggplot(all_metrics, aes(x = nu, y = SAR_median, color = as.factor(beta), group = beta)) +
  geom_line() +
  geom_point() +
  geom_hline(yintercept = 0.2, linetype = "dashed", color = "darkgrey") +
  annotate("rect", xmin = -Inf, xmax = Inf, ymin = 0.2, ymax = 0.3, alpha = 0.3, fill = "lightgrey") +
  geom_hline(yintercept = 0.3, linetype = "dashed", color = "darkgrey") +
  labs(title = 'SAR Median vs Nu for Different Beta Values',
       x = 'nu',
       y = 'SAR Median',
       color = 'Beta') +
  theme_minimal()

### x = beta < 4 AND GREY ZONE FOR SAR
beta <- all_metrics$beta
ggplot(all_metrics, aes(x = beta, y = SAR_median, color = as.factor(nu), group = nu)) +
  geom_line() +
  geom_point() +
  geom_hline(yintercept = 0.2, linetype = "dashed", color = "darkgrey") +
  annotate("rect", xmin = -Inf, xmax = Inf, ymin = 0.2, ymax = 0.3, alpha = 0.3, fill = "lightgrey") +
  geom_hline(yintercept = 0.3, linetype = "dashed", color = "darkgrey") +
  scale_x_continuous("Beta", labels = as.character(all_metrics$beta), breaks = all_metrics$beta) +
  labs(title = 'SAR Median vs Beta for Different Nu Values',
       x = 'Beta',
       y = 'SAR Median',
       color = 'Nu') +
  theme_minimal()


##### HEATMAP
ggplot(all_metrics, aes(x = beta, y = nu, fill = SAR_median)) +
  geom_tile() +
  scale_fill_gradientn(colors = c("red", "yellow", "green", "blue")) +
  labs(title = "2D Surface Plot of Grid Search Results",
       x = "Beta",
       y = "Nu",
       fill = "SAR Median") +
  theme_minimal()

```


```{r}
### 3D SURFACE PLOT USING PLOTLY
library(reshape2)
library(plotly)

# Reshape the data
grid_data <- dcast(all_metrics, beta ~ nu, value.var = "SAR_median")
beta_values <- as.numeric(as.vector(grid_data$beta))
nu_values <- as.numeric(as.vector(colnames(grid_data)[-1]))
SAR_matrix <- as.matrix(grid_data[, -1])


fig <- plot_ly(
  x = ~beta_values,
  y = ~nu_values,
  z = ~SAR_matrix,
  type = 'surface',
  colorscale = list(
    c(0, 'blue'),        # for SAR_median < 0.15
    c(0.15, 'yellow'),   # for SAR_median between 0.15 and 0.25
    c(0.25, 'red'),      # for SAR_median > 0.25
    c(1, 'red')
  ),
  cmin = 0,
  cmax = 1
) %>%
  layout(
    title = '3D Surface Plot of SAR Median',
    scene = list(
      xaxis = list(title = 'Beta'),
      yaxis = list(title = 'Nu'),
      zaxis = list(title = 'SAR Median'),
      aspectmode = 'cube'
    )
  )

fig

## WITH MARKERS = ACTUAL RESULTS
fig <- plot_ly(
  x = ~beta_values,
  y = ~nu_values,
  z = ~SAR_matrix,
  type = 'surface'
) %>%
  add_markers(
    data = all_metrics,
    x = ~beta,
    y = ~nu,
    z = ~SAR_median,
    marker = list(
      color = 'black',
      size = 5,
      symbol = 'circle'
    )
) %>%
  layout(
    title = '3D Surface Plot of SAR Median',
    scene = list(
      xaxis = list(title = 'Beta'),
      yaxis = list(title = 'Nu'),
      zaxis = list(title = 'SAR Median'),
      aspectmode = 'cube'
    )
  )

fig



```

```{r}
#### DISTANCE TO THE SEARCHED SAR
# WE WANT A GLOBAL SAR = 20%
SAR_wanted <- 0.2

# distance to sar
distance_matrix <- 1 - abs(SAR_matrix - SAR_wanted)

fig <- plot_ly(
  x = ~beta_values,
  y = ~nu_values,
  z = ~distance_matrix,
  type = 'surface',
  colorscale = list(
    c(0, 'red'),        # for distance < 0.05
    c(0.7, 'red'),   # for distance between 0.05 and 0.15
    c(0.85, 'yellow'),      # for distance > 0.15
    c(1, 'blue')
  ),
  cmin = 0,
  cmax = 1
) %>%
  layout(
    title = 'Distance to SAR',
    scene = list(
      xaxis = list(title = 'Beta'),
      yaxis = list(title = 'Nu'),
      zaxis = list(title = 'Distance to SAR'),
      aspectmode = 'cube'
    )
  )

fig


## WITH MARKERS = ACTUAL RESULTS
fig <- plot_ly(
  x = ~beta_values,
  y = ~nu_values,
  z = ~distance_matrix,
  type = 'surface'
) %>%
  add_markers(
    data = all_metrics,
    x = ~beta,
    y = ~nu,
    z = ~(abs(SAR_median - SAR_wanted)),
    marker = list(
      color = 'black',
      size = 5,
      symbol = 'circle'
    )
  ) %>%
  layout(
    title = 'Distance to SAR',
    scene = list(
      xaxis = list(title = 'Beta'),
      yaxis = list(title = 'Nu'),
      zaxis = list(title = 'Distance to SAR'),
      aspectmode = 'cube'
    )
  )

fig

```





## SEIR
```{r}
id_global <- global_status %>% distinct(id) %>% pull()
n_individual <- length(id_global)
n_subdivisions <- new_n_subdivisions

list_SEIR <- get_all_SEIR(list_sim = list_sim, n_subdivisions = n_subdivisions)

list_SEIR <- list()

for(couple in names(list_sim)){
  parts <- strsplit(couple, "_")[[1]]
  beta <- eval(parse(text = gsub(pattern = '-', replacement = '/', x = parts[2])))
  nu <- eval(parse(text = gsub(pattern = '-', replacement = '/', x = parts[3])))
  
  list_SEIR[[couple]] <- SEIR_to_list(sim_list = list_sim[[couple]], n_subdivisions = new_n_subdivisions, n_individual = n_individual)

}



```



```{r}
fig_path <- file.path(intervention_path, id_sim, paste0(id_sim,"-fig"))

if (!dir.exists(fig_path)) {
  dir.create(fig_path, recursive = TRUE)
}
```

