---
title: "localisation-nodscov2"
author: "Olivier GAUFRÈS"
date: "2024-05-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
#library(tidyverse)
library(ggplot2)
library(lubridate)
```

```{r}
wd <- getwd()
knitr::opts_chunk$set(root.dir = wd)

data_path <- file.path(wd,"..", "..", "data")
nodscov2_path <- file.path(data_path, "data-nodscov2") 
```

### WIP 

## NodsCov2 data (not shared)
```{r}
load("Y:/ogaufres/projet-pacri/data/data-nodscov2/admission_ctc_nodscov2.RData")
load("Y:/ogaufres/projet-pacri/data/data-nodscov2/list_ward.RData")
```


## FIXING ENCODING
```{r}
Encoding(admission$hospital) <- 'latin1'
```


## Raymond Poincaré reanimation ward
```{r}
data <- list_ward[["Raymond_Poincare-Reanimation-20200506-20200507"]]
admission <- admission %>%
  ## Remove visitors/admin/logistics/investigators
  filter(ward == "Reanimation") %>% 
  filter(hospital == "APHP - RAYMOND POINCARÉ") %>%
  filter(!(cat %in% c("administration",
                  "investigation",
                  "logistic",
                  "visitor"))) %>%
  ## ADD PE/PA IN ADMISSION'S IDs (id)
  mutate(id_bis = paste0(status,"-",id))
## FILTER INTERACTIONS TO KEEP ONLY HCW AND PATIENTS
data <- data %>%
  filter(from %in% admission$id & to %in% admission$id)
  
## ADD INFO OF THE STATUS FOR INDIVIDUALS
data <- left_join(data, admission %>% select(id, status), by = c("from" = "id")) %>%
    rename(from_status = status) %>%
    left_join(admission %>% select(id, status), by = c("to" = "id")) %>%
    rename(to_status = status)
```


## SUBDIVIDING EVERY 30s
```{r}
begin_date <- as.POSIXct(min(data$date_posix_first))
end_date <- as.POSIXct(max(data$date_posix_first + data$length))
time_spent <- end_date - begin_date

n_subdivisions <- as.integer(time_spent) * 24 * 60 * 2 ## Time spent * hours * minutes * 2 (number of time subdivisions)

data_tot <- data.frame()
lin_a <- Sys.time()
for(t in 1:n_subdivisions){
  interactions_t <- data %>%
    filter(date_posix_first <= begin_date + (t)*30 & date_posix_first + length >= begin_date + (t+1)*30) %>%
    mutate(time = t) %>%
    select(from, to, time, from_status, to_status)

  if (dim(interactions_t)[1]!= 0){
  data_tot <- data_tot %>% bind_rows(interactions_t)
  }
}
lin_b <- Sys.time()
print(lin_b-lin_a)
#data_tot <- read.csv2(file = file.path(wd,"..", "..", "data", "data-nodscov2", "int_tot_RP_test.csv"), row.names = F, header = T)
```

## DOUBLE ROOMS
```{r}
## RP reanimation ward has 2 double rooms -> individuals are always in contact (c.f. R/nodscov2/interaction-nodscov2.Rmd)
for(t in 1:n_subdivisions){
  a_df <- data.frame(from = "001-0038-B-S", to = "001-0039-B-F", time = t, from_status = "PA", to_status = "PA")
  b_df <- data.frame(from = "001-0127-B-A", to = "001-0128-Z-K", time = t, from_status = "PA", to_status = "PA")
  data_tot <- bind_rows(data_tot, a_df, b_df)
}
```

## ROOMS
```{r}
rooms <- admission %>%
  filter(status == "PA") %>%
  distinct(id) %>%
  mutate(room = as.factor(row_number())) %>%
  mutate(id_room = as.factor(row_number())) %>%
  select(id_room,room, id)

rooms <- rooms %>%
  bind_rows(data.frame(room = "Restroom", id = "PE", id_room = as.factor(nrow(rooms) + 1))) %>%
  bind_rows(data.frame(room = "Corridor", id = "ALL", id_room = as.factor(nrow(rooms) + 2)))

## "001-0038-B-S" and = "001-0039-B-F" are in the same room
## "001-0127-B-A" and "001-0128-Z-K" are in the same room
rooms <-rooms %>% mutate(room = ifelse(id == "001-0038-B-S", rooms[rooms$id == "001-0039-B-F", "room"], room),
                         id_room = ifelse(id == "001-0038-B-S", rooms[rooms$id == "001-0039-B-F", "id_room"], id_room))

rooms <-rooms %>% mutate(room = ifelse(id == "001-0128-Z-K", rooms[rooms$id == "001-0127-B-A", "room"], room),
                         id_room = ifelse(id == "001-0128-Z-K", rooms[rooms$id == "001-0127-B-A", "id_room"], id_room))

```


## INTERACTION LOCALISATION
```{r}
data_tot <- data_tot %>% 
  mutate(localisation = NA)  # Initialize localisation column with NA

# Join data_tot with rooms based on the common column (id) for 'from'
data_tot <- data_tot %>%
  left_join(rooms, by = c("from" = "id")) %>%  ## .x join
  left_join(rooms, by = c("to" = "id")) %>% ## .y join
  mutate(localisation = case_when(
    from %in% c("001-0038-B-S", "001-0039-B-F") | to %in% c("001-0038-B-S", "001-0039-B-F") ~ rooms[rooms$id == "001-0038-B-S", "id_room"],
    from %in% c("001-0127-B-A", "001-0128-Z-K") | to %in% c("001-0127-B-A", "001-0128-Z-K") ~ rooms[rooms$id == "001-0127-B-A", "id_room"],
    from_status == "PE" & to_status == "PE" ~ rooms[rooms$id == "PE" , "id_room"],
    from_status == "PA" & to_status == "PE" ~ id_room.x,
    from_status == "PE" & to_status == "PA" ~ id_room.y,
  )) %>%
  select(-room.x, -id_room.x, -room.y, -id_room.y)
```

## LOCALISATION INFERENCE
```{r}
global_localisation <- data.frame()


ta <- Sys.time()
overlap <- data.frame()
for (t in 1:n_subdivisions){
  for (individual in admission$id){
    if (dim(data_tot %>% filter(from == individual | to == individual) %>% filter(time == t) %>% distinct(localisation))[1] > 1){
      overlap <- bind_rows(overlap, data_tot %>% filter(from == individual | to == individual) %>% filter(time == t) )
    }
  }
}
tb <- Sys.time()
print(tb-ta)
## 18min 07/05/24

    # previous_int <- data_tot %>% filter(from == individual | to == individual) %>% filter(time == t-1)
    # current_int <- data_tot %>% filter(from == individual | to == individual) %>% filter(time == t)
    # future_int <- data_tot %>% filter(from == individual | to == individual) %>% filter(time == t+1)
    # overlap <- current_int %>% distinct(localisation)
```

```{r}


for(t in 234:234){
  localisation_ti <- data.frame(id = admission$id, loc = NA)
  interactions <- data_tot %>% filter(time == t)
  id_no_int <- admission %>% filter(!(id %in% interactions$from) & !(id %in% interactions$to))
  id_int <- admission %>% filter(!(id %in% id_no_int$id))
  
  
  
  unique_individuals <- unique(c(interactions$from, interactions$to))
  individual_network <- lapply(unique_individuals, function(individual) {
    a = interactions %>%
      filter(from == individual | to == individual)
    a = c(a$from,a$to) %>% setdiff(individual)
    })
    names(individual_network) <- unique_individuals

    for (j in id_int$id){
      status <- admission[admission$id == j, "status"]
    
      if  (status == "PA"){
      localisation_ti[admission$id == j, "loc"] <- rooms[rooms$id == j, "id_room"]
      }
      
      if  (status == "PE"){
        if( length(individual_network[[j]]) == 1){## j is only interacting with 1 individual
        localisation_ti[admission$id == j, "loc"] <- interactions %>% filter(from == j | to == j) %>% distinct(localisation) %>% pull(localisation) ##### TEMPORARY ISSUS SAME INTERACTION TWICE
        }
      
        if (  dim(interactions %>% filter(from == j | to == j) %>% filter(localisation < 19) %>% select(localisation))[1] != 0) {
          localisation_ti[admission$id == j, "loc"] <- interactions %>% filter(from == j | to == j) %>% filter(localisation < 19) %>% pull(localisation)
        }
        else{
          localisation_ti[admission$id == j, "loc"] <- rooms[rooms$id == "PE", "id_room"]
        }
      }
    }
    
  for (i in id_no_int$id){
    status <- admission[admission$id == i, "status"]
    
    if  (status == "PA"){
      ## Rules for patients that don't have an interaction
      ## Patients stay in their room (thus if not in Restroom (chamber or corridor), they will go to their room)
      room_assigned <- rooms[admission$id == i, "id_room"]
      localisation_ti[admission$id == i, "loc"] <- room_assigned
    }
    
    if  (status == "PE"){
      ## Rules for HCWs that don't have an interaction
      # If at t-1, the HCW is either in the corridor/restroom, he will go/stay to the restroom and if he was in a patient's room, he will go to the corridor
      room_assigned <- rooms[rooms$id == "PE", "id_room"]
      room_prev <- global_localisation %>% filter(time == t-1, id == i) %>% pull(loc)
      # If HCW was in a patient's room -> Corridor
      if (room_prev <= 19 & room_prev >= 1){ # 19 -> id of restroom/corridor /!\ TEMPORARY
        localisation_ti[admission$id == i, "loc"] <- rooms[rooms$id == "PE", "id_room"]
      }
      # If HCW is in the Corridor/Restroom  -> Restroom /!\ TEMPORARY because ind. are leaving (ti-2 etc?)
      else{
        localisation_ti[admission$id == i, "loc"] <- rooms[rooms$id == "PE", "id_room"]
      }
    }
  }
}
```



