---
title: "model-nodscov2"
author: "Olivier GAUFRÈS"
date: "2024-05-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(Rcpp)
```

```{r}
wd <- getwd()
knitr::opts_chunk$set(root.dir = wd)
args = commandArgs(trailingOnly=TRUE)

cpp_path <-  file.path(wd,"..", "..", "cpp")
cpp_model_path <- file.path(cpp_path,"nodscov2")
sim_nodscov2_path <- file.path(wd, "..", "..", "out", "sim-nodscov2")
loc_nodscov2_path <- file.path(wd, "..", "..", "out", "loc-nodscov2")

if (!dir.exists(sim_nodscov2_path)) {
  dir.create(sim_nodscov2_path, recursive = TRUE)
}
```

## NodsCov2 data (not shared)
```{r}
#load("Y:/ogaufres/pacri-non-sync/data/data-nodscov2/admission_ctc_nodscov2.RData")
#load("Y:/ogaufres/pacri-non-sync/data/data-nodscov2/list_ward.RData")
#load(file.path(loc_nodscov2_path,"localization-nodscov2.RData")) ##overwrite admission

##dev
load(file.path(loc_nodscov2_path,"dev-localization-nodscov2.RData")) ##overwrite admission
```

## ADMISSION
```{r}
admission_sim <- admission %>%
  mutate(info = ifelse(status == "PE", 1,0)) %>%
  select(id,info) %>%
  mutate(id_ind = id) %>% 
  left_join(rooms, by = c("id_ind" = "id")) %>%
  mutate(room = ifelse(info == 1, rooms[rooms$id == "M-PM", "id_room"], room)) %>%
  select(id,info,room)
admission_sim$info <- as.integer(admission_sim$info)
admission_sim$room <- as.integer(admission_sim$room)
```

## ROOMS
```{r}
#head(rooms)
```

## INTERACTIONS
```{r}
#head(global_interaction)
```

## LOCALIZATIONS
```{r}
#head(global_localization)
```

## ENVIRONMENT
```{r}
env_t <- rooms %>%
  distinct(room) %>%
  mutate(env = 0) %>%
  mutate(id_room = rooms %>% distinct(id_room) %>% pull() ) %>%
  select(room, id_room, env)
env_t$id_room <- as.integer(env_t$id_room)

global_environment <- lapply(1:n_subdivisions, function(t){
  return (env_t)
})

rm(env_t)
```

## STATUS
```{r}
global_status = data.frame(id = admission$id, t_inf = as.integer(-1), t_incub = as.integer(-1), t_recover = as.integer(-1), inf_by = "", inf_room = as.integer(-1))
```

## LAMBDA
```{r}
lambda_t <- admission %>%
  distinct(id) %>%
  mutate(lambda_c = 0, lambda_e = 0)
global_lambda <- lapply(1:n_subdivisions, function(t){
  return(lambda_t)
})
rm(lambda_t)
```


### SIMULATION

## Rcpp
```{r}
#load("~/CNAM-PASTEUR-FIXE/projet-pacri/data-model-nodscov.RData")
sourceCpp(file.path(cpp_model_path,"model-nodscov2.cpp"))
```

## PARAMETERS
```{r}
beta <- 4
epsilon <- 1
mu <- 1
nu <- 1
dt <- 30
tau <- 60 * 60 *24
deltat <- dt/tau
env_thresold <- 0
```

## INDEX
```{r}
id_index <- "001-0038-B-S"
status <- global_status %>% mutate(t_inf = ifelse(id == id_index,
                                                  as.integer(1),
                                                  t_inf),
                                   t_incub = ifelse(id == id_index,
                                                    as.integer(t_inf + runif(1, min = 2880*1, max = 2880*5)),
                                                    t_recover),
                                   t_recover = ifelse(id == id_index,
                                                      as.integer(t_incub + runif(1, min = 2880*3, max = 2880*7)),
                                                      t_recover),
                                   inf_by = ifelse(id == id_index,
                                                   "INDEX",
                                                   inf_by))
```

## Simulation
```{r}
data_sim <- simulation(global_interaction = global_interaction,
           global_localization = global_localization,
           global_environment = global_environment,
           global_lambda = global_lambda,
           global_status = status,
           admission = admission_sim,
           beta = beta,
           epsilon = epsilon,
           nu = nu,
           mu = mu,
           env_thresold,
           dt = dt
           )
```

#SAVE TO .RData FILES
```{r}
id_sim <- ifelse(length(args)==0, "01", args[1])
save(global_interaction,
     global_localization,
     admission,
     admission_sim,
     rooms,
     beta,
     nu,
     mu,
     env_thresold,
     dt,
     n_subdivisions,
     begin_date,
     end_date,
     data_sim,
     clusters,
     file = file.path(sim_nodscov2_path, paste0(id_sim, "-", "simulation-nodscov2.RData"))
     )
```


## WIP ##
## endless day

```{r}
end_date - begin_date ##end of last interaction
## we take 24h
new_begin_date <- begin_date + 5*60*60
new_end_date <- new_begin_date + 24*60*60
new_end_date - new_begin_date
t_begin <- 5*60*2
t_end <- (t_begin + 24*60*2) - 1
```


```{r}
truncated_interaction <- global_interaction[(u <- seq_along(global_interaction)) %in% t_begin:(t_end)]
truncated_localization <- global_localization[(u <- seq_along(global_localization)) %in% t_begin:(t_end)]
truncated_lambda <- global_lambda[(u <- seq_along(global_lambda)) %in% t_begin:(t_end)]
truncated_environment <- global_environment[(u <- seq_along(global_environment)) %in% t_begin:(t_end)]
truncated_status <- status
```

## ENDLESS DAY OBJECTS
```{r}
n_days <- 28
test_interaction <- rep(truncated_interaction, n_days)
test_localization <- rep(truncated_localization, n_days)
test_lambda <- rep(truncated_lambda, n_days)
test_environment <- rep(truncated_environment, n_days)
test_status <- truncated_status

new_n_subdivisions <- (t_end-t_begin +1)*n_days
```



```{r}
ta <- Sys.time()
data_sim_test <- simulation(global_interaction = test_interaction,
           global_localization = test_localization,
           global_environment = test_environment,
           global_lambda = test_lambda,
           global_status = test_status,
           admission = admission_sim,
           beta = beta,
           epsilon = epsilon,
           nu = nu,
           mu = mu,
           env_thresold,
           dt = dt
           )
tb <- Sys.time()
print(tb-ta)
```



```{r}
id_sim <- ifelse(length(args)==0, "test-endless-day", args[1])

save(truncated_interaction,
     truncated_localization,
     admission,
     admission_sim,
     rooms,
     beta,
     nu,
     mu,
     env_thresold,
     dt,
     new_n_subdivisions,
     n_days,
     new_begin_date,
     new_end_date,
     data_sim_test,
     clusters,
     file = file.path(sim_nodscov2_path, paste0(id_sim, "-", "simulation-nodscov2.RData"))
     )
```

