---
title: "pathogens-analysis"
author: "Olivier GAUFRÈS"
date: "2024-07-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(lubridate)
library(tidyr)
library(visNetwork)
library(ggborderline)
```

```{r}
wd <- getwd()
knitr::opts_chunk$set(root.dir = wd)
out_path <- file.path(wd,'..','..','out')
loc_path <- file.path(out_path, "loc-nodscov2")
sensibility_path <- file.path(out_path,'sensibility-analysis')
```


```{r}
###########
## PATHS ##
###########
beta <- 3
beta <- 'mean'
beta <- 'median'

wd <- getwd()
loc_path <- file.path(wd,'..','..', 'out','loc-nodscov2','dev-localization-nodscov2.RData')
pathogens_path <- file.path(wd,'..','..', 'out', 'pathogens-analysis')
RData_path <- file.path(pathogens_path, paste0('sim-beta-', beta), paste0('parameters-model-beta-', beta, '.RData'))
cpp_path <- file.path(wd, '..', '..', 'cpp', 'nodscov2', 'dev-sensibility-analysis.cpp')

####################
## RDATA AND RCPP ##
####################
load(RData_path)
sourceCpp(cpp_path)

```


```{r}
## PATHOGEN CONTRIBUTION
contrib_C <- 0.6
contrib_E <- 0.4
```


```{r}
##cat
cat_paramedical <- c("nurse", "student nurse", "aux nurse")
cat_medical <- c("physician", "ext physician", "reeducation staff", "other")
## IDS BY CATEGORY
id_paramedical <- admission_sim %>% pull(id)
id_medical <- admission_sim %>% pull(id)
id_hcw <- admission_sim %>% pull(id)
id_patient <- admission_sim %>% pull(id)

## N
n_PM <- length(id_paramedical)
n_M <- length(id_medical)
n_HCW <- length(id_hcw)
n_PA <- length(id_patient)
```

## Pathogens
```{r}
list_pathogen <- c('HCov', 'IV', 'SRV', 'Staphylococcus-Aureus', 'Acinetobacter-baumannii')
list_intervention ('Baseline', 'Masks', 'Ventilation')

list_parameters <- list()

launch_simulation <- function(pathogen, intervention, beta, nu, q, mu){
  
}
```


## Simulation (cluster)
```{r}
load_rdata_to_list <- function(file, ) {
  load(file)
  file_name <- basename(file)
  sim_id <- sub("sim-(\\d+)-.*", "\\1", file_name)
  sim_type <- sub("sim-\\d+-(.*)\\.RData", "\\1", file_name)
  object_name <- paste0("sim_", sim_id, "_", sim_type)
  ## Put in list according to sim_type
  if (sim_type == "C") {
    sim_C[[sim_id]] <<- get(object_name)
  } else if (sim_type == "E") {
    sim_E[[sim_id]] <<- get(object_name)
  } else if (sim_type == "CE") {
    sim_C_E[[sim_id]] <<- get(object_name)
  }
}


for (pathogen in list_pathogen){
  
  for (intervention in list_intervention){
    
    assign(x = paste0('sim-', pathogen, '-', intervention), value = list())
    sim_path <- file.path(pathogens_path, paste0('sim-', pathogen, '-', intervention), 'RData')
    rdata_files <- list.files(sim_path, pattern = "^sim-.*\\.RData$", full.names = TRUE)
    
    lapply(rdata_files, load_rdata_to_list)
    
    
  }
}
```



## Secondary attack rates
```{r}
SAR_HCW <- n_inf_HCW / n_HCW
SAR_PA <- n_inf_PA / n_PA
SAR_M <- n_inf_M / n_M
SAR_PM <- n_inf_PM / n_PM

## Boxplots

```

## Outbreak duration
```{r}

```


