---
title: "temp-model-nodscov2"
author: "Olivier GAUFRÈS"
date: "2024-05-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
#library(tidyverse)
library(ggplot2)
library(lubridate)
library(Rcpp)
library(RcppParallel)
```

```{r}
wd <- getwd()
knitr::opts_chunk$set(root.dir = wd)

data_path <- file.path(wd,"..", "..", "data")
nodscov2_path <- file.path(data_path, "data-nodscov2")
cpp_path <-  file.path(wd,"..", "..", "cpp")
cpp_model_path <- file.path(cpp_path,"nodscov2")
```

### WIP 

## NodsCov2 data (not shared)
```{r}
load("Y:/ogaufres/pacri-non-sync/data/data-nodscov2/admission_ctc_nodscov2.RData")
load("Y:/ogaufres/pacri-non-sync/data/data-nodscov2/list_ward.RData")
load(file.path(wd,"localization-nodscov2.RData")) ##overwrite admission
```

## FIXING ENCODING
```{r}
Encoding(admission$hospital) <- 'latin1'
```

```{r}
## FILTER THE DATAFRAMES
list_ward <- lapply(list_ward, function(x) {
  ## FILTER INTERACTIONS TO KEEP ONLY HCW AND PATIENTS
  x <- x%>% filter(from %in% admission$id & to %in% admission$id)
  ## ADD INFO OF THE STATUS FOR INDIVIDUALS
  x <- left_join(x, admission %>% select(id, status), by = c("from" = "id")) %>%
    rename(from_status = status) %>%
    left_join(admission %>% select(id, status), by = c("to" = "id")) %>%
    rename(to_status = status)
})

data <- list_ward[["Raymond_Poincare-Reanimation-20200506-20200507"]]

# admission <- admission %>%
#   filter(ward == "Reanimation") %>% 
#   filter(hospital == "APHP - RAYMOND POINCARÉ") %>%
#   filter(!(cat %in% c("administration",
#                   "investigation",
#                   "logistic",
#                   "visitor"))) %>%
#   ## ADD PE/PA IN ADMISSION'S IDs (id)
#   mutate(id_bis = paste0(status,"-",id))
```

## TEMPORARY
```{r}
## plans are more detailled for Raymond Poincaré hospital
## Dimensions
begin_date
end_date
time_spent <- end_date - begin_date
time_spent
n_subdivisions
n_individuals <- as.integer(admission %>%
                              filter(hospital == "APHP - RAYMOND POINCARÉ", ward == "Reanimation") %>%
                              distinct(id) %>%
                              count())
n_individuals
# begin_date <- as.POSIXct(min(data$date_posix_first))
# end_date <- as.POSIXct(max(data$date_posix_first + data$length))
# n_subdivisions <- as.integer(time_spent) * 24 * 60 * 2 ## Time spent * hours * minutes * 2 (number of time subdivisions)
```

## INTERACTIONS
```{r}
global_interaction <- data_list
```

## ROOMS
```{r}
## LOADED WITH .RData (localisation-nodscov2.Rmd)
rooms

# rooms <- admission %>%
#   filter(status == "PA") %>%
#   distinct(id) %>%
#   mutate(room = as.factor(row_number())) %>%
#   mutate(id_room = as.factor(row_number())) %>%
#   select(id_room,room, id)
# 
# rooms <- rooms %>%
#   bind_rows(data.frame(room = "Restroom", id = "PE", id_room = as.factor(nrow(rooms) + 1))) %>%
#   bind_rows(data.frame(room = "Corridor", id = "ALL", id_room = as.factor(nrow(rooms) + 2)))
# 
# ### DOUBLE ROOMS
# ## "001-0038-B-S" and = "001-0039-B-F" are in the same room
# ## "001-0127-B-A" and "001-0128-Z-K" are in the same room
# rooms <-rooms %>% mutate(room = ifelse(id == "001-0038-B-S", rooms[rooms$id == "001-0039-B-F", "room"], room),
#                          id_room = ifelse(id == "001-0038-B-S", rooms[rooms$id == "001-0039-B-F", "id_room"], id_room))
# 
# rooms <-rooms %>% mutate(room = ifelse(id == "001-0128-Z-K", rooms[rooms$id == "001-0127-B-A", "room"], room),
#                          id_room = ifelse(id == "001-0128-Z-K", rooms[rooms$id == "001-0127-B-A", "id_room"], id_room))
# 
double_rooms <- list(c("001-0038-B-S", "001-0039-B-F"), c("001-0127-B-A", "001-0128-Z-K"))
```

## ENVIRONMENT
```{r}
env_t <- rooms %>%
  distinct(room) %>%
  mutate(env = 0) %>%
  mutate(id_room = rooms %>% distinct(id_room) %>% pull() ) %>%
  select(room, id_room, env)
env_t$id_room <- as.integer(env_t$id_room)

global_environment <- lapply(1:n_subdivisions, function(t){
  return (env_t)
})

rm(env_t)
```

## LOCALISATION
```{r}
## LOADED WITH .RData (localization-nodscov2.Rmd)


## REMOVE "NOT HERE" FROM global_localization[[t]]$localization (in order to have an integer vector)
global_localization <- lapply( 1:n_subdivisions, function(t){
  loc_t <- global_localization[[t]]
  loc_t <- loc_t %>% mutate(localization = ifelse(localization == "NOT HERE", -1, localization))
  loc_t$localization <- as.integer(loc_t$localization)
  return(loc_t)
})
head(global_localization)


```

## STATUS
```{r}
# status_t <- admission %>%
#   distinct(id) %>%
#   mutate(status = 0)
# 
# global_status <- lapply(1:n_subdivisions, function(t){
#   return(status_t)
# })
# rm(status_t)
global_status = data.frame(id = admission$id, t_inf = as.integer(-1), t_recover = as.integer(-1), inf_by = "", inf_room = as.integer(-1))

```


## LAMBDA
```{r}
lambda_t <- admission %>%
  distinct(id) %>%
  mutate(lambda_c = 0, lambda_e = 0)
global_lambda <- lapply(1:n_subdivisions, function(t){
  return(lambda_t)
})
rm(lambda_t)
```
## INFO_PATIENT_HCW
```{r}
##CHANGE STATUS FOR INFO  (PA -> 0 AND PE -> 1)
admission_test <- admission %>%
  mutate(info = ifelse(status == "PE", 1,0)) %>%
  select(id,info) %>%
  mutate(id_ind = id) %>% 
  left_join(rooms, by = c("id_ind" = "id")) %>%
  mutate(room = ifelse(info == 1, rooms[rooms$id == "PE", "id_room"], room)) %>%
  select(id,info,room)
admission_test$info <- as.integer(admission_test$info)
admission_test$room <- as.integer(admission_test$room)

```


## GLOBAL DATABASE
```{r}
## global_interaction
## global_localization
## global_environment
## global_status
## global_lambda


## inferred_admission (if needed?)
## HCW_interacting_id (if needed?)
## double_rooms (if needed?)


## begin_date (if needed?)
## end_date (if needed?)
## n_subdivisions

## clusters (if needed?)
```


```{r}
#load("~/CNAM-PASTEUR-FIXE/projet-pacri/test-model.RData")
sourceCpp(file.path(cpp_model_path,"model-nodscov2.cpp"))

## PARAMETERS
beta <- 200
epsilon <- 50
mu <- 5
nu <- 5
dt <- 30
tau <- 60 * 60 *24
deltat <- dt/tau
#INDEX
id_index <- "001-0038-B-S"
test_status <- global_status %>% mutate(t_inf = ifelse(id == id_index, as.integer(1), t_inf ),
                                      t_recover = ifelse(id == id_index, as.integer(1000), t_recover ),
                                      inf_room = ifelse(id ==id_index, rooms[rooms$id == id_index, "id_room"], inf_room),
                                      inf_by = ifelse(id == id_index, "INDEX", inf_by))



sourceCpp(file.path(cpp_model_path,"model-nodscov2.cpp"))

a <- Update_status_bis(test_status, test_lambda, admission_test, global_interaction[[2]], global_localization[[2]], t=2)
b <- Get_status_t(a,300)
loc_test <- Get_loc_HCW("001-0001-D-J",admission_test, global_localization[[1]])
Get_status_j("001-0038-B-S", test_status, admission_test, 1)
Get_loc_j("001-0021-S-G", admission_test, global_localization[[1]])


tsima <- Sys.time()
test <- simulation(global_interaction = global_interaction,
           global_localization = global_localization,
           global_environment = global_environment,
           global_lambda = global_lambda,
           global_status = test_status,
           info_patient_HCW = admission_test,
           beta = beta,
           epsilon = epsilon,
           nu = nu,
           mu = mu,
           dt = dt
           )
tsimb <- Sys.time()
print(tsimb-tsima)

res_lambda <- test[["global_lambda"]]
res_status <- test[["global_status"]]
```


## Vizualisation
```{r}
## Number of infected over time
counts <- sapply(1:n_subdivisions, function(t) {
  sum(test[["global_status"]]$t_inf <= t &
        test[["global_status"]]$t_recover >= t &
        test[["global_status"]]$t_inf != -1)
})

infected_over_time <- data.frame(time = 1:n_subdivisions, infected_count = counts)

ggplot(infected_over_time, aes(x = time * 30 + begin_date, y = infected_count)) +
  geom_line(color = "blue") +
  labs(title = "Number of Infected Individuals Over Time",
       x = "Time",
       y = "Number of Infected Individuals") +
  theme_bw()+
  theme(axis.text.x=element_text(angle=45, hjust=1))

```

## Viral load
```{r}
viral_load_over_time <- do.call(rbind, lapply(1:length(test[["global_environment"]]), function(t) {
  data.frame(time = begin_date + 30 * t,
             room = test[["global_environment"]][[t]]$room,
             viral_load = test[["global_environment"]][[t]]$env)
}))

ggplot(viral_load_over_time, aes(x = time, y = viral_load, color = factor(room))) +
  geom_line() +
  labs(title = "Viral Load in Rooms Over Time",
       x = "Time",
       y = "Viral Load",
       color = "Room") +
  theme_bw() +
  theme(axis.text.x=element_text(angle=45, hjust=1))
```


## FOI
```{r}
hcw_id <- admission %>% filter(status == "PE") %>% pull(id)


FOI_over_time <- do.call(rbind, lapply(1:length(test[["global_lambda"]]), function(t) {
  data.frame(time = begin_date + 30 * t,
             id = test[["global_lambda"]][[t]]$id,
             lambda_e = test[["global_lambda"]][[t]]$lambda_e,
             lambda_c = test[["global_lambda"]][[t]]$lambda_c,
             status = ifelse(test[["global_lambda"]][[t]]$id %in% hcw_id, "PE", "PA"))
}))

ggplot(FOI_over_time, aes(x = time)) +
  geom_line(aes(y = lambda_e, colour = "lambda_e (environment)" ), alpha = 0.5) +
  geom_line(aes(y = lambda_c, colour = "lambda_c (close-contact)" ), alpha = 0.5) +
  labs(title = "Lambda Over Time",
       x = "Time",
       y = "Lambda",
       color = "Lambda") +
  facet_grid(cols = vars(status)) + 
  theme_bw() + 
  theme(axis.text.x=element_text(angle=45, hjust=1))
```


```{r}
FOI_over_time <- FOI_over_time %>% mutate(p_inf = 1 - exp(-lambda_e - lambda_c))

ggplot(FOI_over_time, aes(x = time)) +
  geom_line(aes(y = lambda_e, colour = "P_inf" )) +
  labs(title = "Probability of infection Over Time",
       x = "Time",
       y = "P_inf",
       color = "P_inf") +
  facet_grid(cols = vars(status)) + 
  theme_bw() +
  theme(axis.text.x=element_text(angle=45, hjust=1))

```


## REBUILD GLOBAL_INTERACTION WITH CORRECT LOCALIZATION
```{r}
test_global_int <- global_interaction

# FOR EACH t
for (t in 1:length(test_global_int)) {
  interactions <- test_global_int[[t]]
  cluster <- clusters[[t]]
  
  # FOR EACH INT 
  for (j in 1:nrow(interactions)) {
    interaction <- interactions[j, ]
    id_from <- interaction$from ##from and to are in the same cluster
    # CLUSTER ASSOCIATED WITH THIS INTERACTION
    cluster_id <- NA  
    for (k in 1:length(cluster)) {
      if (id_from %in% cluster[[k]]) {
        cluster_id <- k
        break
      }
    }
    localization <- "NOT ASSIGNED"
    # ID ROOM
    if (interaction$from_status == "PA" & interaction$to_status == "PA"){ ## IF PA-PA
      localization1 <- rooms[rooms$id == interaction$from, "id_room"] ## DOUBLE ROOM, FROM/TO SAME THING
      localization2 <- rooms[rooms$id == interaction$to, "id_room"]
      localization <- ifelse(localization1 == localization2, localization1, "PROBLEM PA-PA NOT SAME ROOM")
    } else{ # IF PE-PE OR PA-PE OR PE-PA -> CAUTION, GLOBAL_LOCALIZATION ONLY TRACK HCW (PE) LOCALIZATION, WE CANNOT ACCESS TO CLUSTER'S LOCALIZATION USING A PATIENT (PA) ID
      patient_id <- ifelse(interaction$from_status == "PA", interaction$to, interaction$from)
      patient_room <- rooms[rooms$id == patient_id, "id_room"]
      localization <- global_localization[[t]] %>% filter(id == patient_id) %>% pull(localization)
    }

    # EDIT GLOBAL_INTERACTION
    test_global_int[[t]]$cluster_id[j] <- cluster_id
    test_global_int[[t]]$localization[j] <- localization
  }
}
## OK
loc_reel <- global_localization[[100]] %>% filter(localization != -1) %>% filter(id %in% test_global_int[[100]]$from | id %in% test_global_int[[100]]$to )
int_test <- test_global_int[[100]]


```


## INFECTION CHAIN
```{r}
library(epicontacts)

## linelist object
linelist <- left_join(admission_test, res_status, by = join_by(id))
linelist <- linelist %>%
  mutate(type = ifelse(info == 0, "PATIENT", "HEALTHCARE WORKER")) %>%
  mutate(type = ifelse(id == id_index, "INDEX", type)) 

env_linelist <- data.frame(id = paste0("ENVIRONMENT-",rooms %>% distinct(id_room, .keep_all = TRUE) %>% pull(id_room)),
                           type = "ROOM",
                           room = rooms %>% distinct(id_room, .keep_all = TRUE) %>% pull(id_room))

linelist <- bind_rows(linelist,env_linelist)


## contacts object
environmental_contacts <- res_status %>%
  filter(grepl("ENVIRONMENT", inf_by)) %>%
  mutate(from = inf_by, to = id, time = t_inf) %>%
  mutate(cause = "ENVIRONMENT") %>% 
  select(from, to, t_inf, t_recover, inf_by, cause)


close_contacts <- res_status %>%
  filter(grepl("CONTACT", inf_by)) %>%
  mutate(from = gsub("CONTACT-", "", inf_by), to = id, time = t_inf) %>%
  mutate(cause = "CONTACT") %>% 
  
  select(from, to, t_inf, t_recover, inf_by, cause)

inf_contacts_df <- bind_rows(environmental_contacts, close_contacts)
inf_contacts_df <- inf_contacts_df %>% mutate(inf_interval = paste0("{",t_inf,";", t_recover,"}"))

## epicontacts object
x <- make_epicontacts(linelist = linelist,
                      contacts = inf_contacts_df,
                      id = "id",
                      from = "from",
                      to = "to",
                      directed = FALSE)

## plot epicontacts
plot(x,
     node_color = "type",
     edge_color = "cause",
     edge_label = "inf_interval",
     label = "room",
     thin = TRUE)


## NOT WORKING
#node_colors <- setNames(c("red", "blue", "black","darkgreen"), c("PATIENT", "HEALTHCARE WORKER", "INDEX","ROOM"))
```



<!-- ################################# GARBAGE ############################## -->

```{r}
res_status <- test[["global_status"]]
test_order <- res_status %>% filter(t_inf != -1)

test_no_inf <- res_status %>% filter(t_inf == -1)
test_env <- test_order %>% filter(substr(inf_by,1, 12) == "ENVIRONMENT-")
test_contact <- test_order %>% filter(substr(inf_by,1,8) == "CONTACT-")
test_index <- test_order %>% filter(inf_by == "INDEX")

dim(test_env)[1] + dim(test_contact)[1] + dim(test_index)[1] + dim(test_no_inf)[1] == dim(res_status)[1]
```




