---
title: "visualization-nodscov2"
author: "Olivier GAUFRÈS"
date: "2024-05-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(ggpubr)
library(lubridate)
library(tidyr)
library(visNetwork)
# Sys.setlocale("LC_ALL", "English")
Sys.setlocale("LC_ALL", "en_US.UTF-8")

```

```{r}
wd <- getwd()
knitr::opts_chunk$set(root.dir = wd)

out_path <- file.path(wd, "..", "..", "out")
cpp_path <-  file.path(wd,"..", "..", "cpp")
cpp_model_path <- file.path(cpp_path,"nodscov2")
sim_nodscov2_path <- file.path(out_path, "sim-nodscov2")
loc_path <- file.path(out_path,'loc-nodscov2')

id_sim <- "01"
id_sim_path <- file.path(sim_nodscov2_path, id_sim)
fig_sim_path <- file.path(id_sim_path, paste0(id_sim,"-fig"))


if (!dir.exists(fig_sim_path)) {
  dir.create(fig_sim_path, recursive = TRUE)
}
```


## TEST
```{r}
# id_sim <- "dev-test-endless-day"
# id_sim_path <- file.path(sim_nodscov2_path, id_sim)
# fig_sim_path <- file.path(id_sim_path, 'UNIQUE', paste0(id_sim,"-fig"))
# 
# if (!dir.exists(fig_sim_path)) {
#   dir.create(fig_sim_path, recursive = TRUE)
# }
# 
# load(file.path(id_sim_path, paste0(id_sim, "-", "unique-simulation-nodscov2.RData")))


## intervention analysis
intervention_path <- file.path(out_path, 'intervention-analysis')
load(file.path(loc_path, 'dev-localization-nodscov2.RData'))
load(file.path(intervention_path, "parameters-admission-nodscov2.RData"))
load(file.path(intervention_path, "scenario-3-unique-simulation-nodscov2.RData"))
fig_sim_path <- file.path(intervention_path, 'fig', 'UNIQUE')
## TEMP
admission <- admission %>% filter(id %in% admission_sim$id)

# global_interaction <- rep(truncated_interaction, n_days)
# global_localization <- rep(truncated_localization, n_days)
new_begin_date <- begin_date + t_begin*30 ## OFFSET TO START THE DAY AT 12AM
new_end_date <- new_begin_date + new_n_subdivisions*30
print(new_end_date - new_begin_date)
```

## REMOVE INDIVUDUALS NOT INTERACTING DURING THE SIMULATION
```{r}
id_interacting <- admission_sim %>% distinct(id) %>% pull()
# id_interacting <- do.call(rbind,truncated_interaction) %>%
#   pivot_longer(cols = c(from, to), names_to = "direction", values_to = "individual") %>%
#   distinct(individual) %>%
#   pull()
# id_total <- admission %>% distinct(id) %>% pull()
# id_not_interacting <- setdiff(id_total, id_interacting)

```


## Vizualisation
```{r}
## Number of infected over time
n_individual <- length(id_interacting)
n_subdivisions <- new_n_subdivisions
status_sim <- data_sim$global_status

## SEIR counts w/ matrix +++ faster than df (before)
SEIR_counts <- function(status_sim, n_subdivisions, n_individual) {
  ## Time steps
  times <- seq(1, n_subdivisions, 1)
  ##DF
  counts_df <- data.frame(
    Susceptible = colSums(outer(status_sim$t_inf, times, function(x, y) x == -1 | x > y)),
    Exposed = colSums(outer(status_sim$t_inf, times, function(x, y) x <= y) & outer(status_sim$t_incub, times, function(x, y) x > y)),
    Infectious = colSums(outer(status_sim$t_incub, times, function(x, y) x <= y) & outer(status_sim$t_recover, times, function(x, y) x > y)),
    Recovered = colSums(outer(status_sim$t_recover, times, function(x, y) x <= y) & outer(status_sim$t_inf, times, function(x, y) x != -1)),
    time = times
  )
  ## Pivot for easier plot
  counts_df <- counts_df %>%
    pivot_longer(cols = c("Susceptible", "Exposed", "Infectious", "Recovered"), names_to = "status", values_to = "count") %>%
    mutate(proportion = count * 100 / n_individual)
  ## ## S E I R as factor 
  counts_df$status <- factor(counts_df$status, levels = c("Susceptible", "Exposed", "Infectious", "Recovered"))
  
  return(counts_df)
}

counts_df <- SEIR_counts(status_sim,
                         n_subdivisions,
                         n_individual)
```

## SEIR
```{r}
dir.create(file.path(fig_sim_path, 'SEIR'))
## Custom colors
SEIR_colors <- c("Susceptible" = "green", "Exposed" = "pink", "Infectious" = "red", "Recovered" = "blue")

## PLOTS
SEIR_n <- ggplot(counts_df, aes(x = time * 30 + begin_date, y = count, color = factor(status))) +
  geom_line(linewidth = 1) +
  labs(title = "SEIR",
       x = "Time",
       y = "Number of individuals",
       color = "Status") +
  labs(title='') +
  scale_color_manual(values = SEIR_colors) +
  # theme(axis.text.x=element_text(angle=45, hjust=1)) +
  theme_bw()
print(SEIR_n)
ggsave(file = file.path(fig_sim_path, 'SEIR', paste0(id_sim, "-SEIR-n.png")), plot = SEIR_n, height = 3, width = 9)

SEIR_p <- ggplot(counts_df, aes(x = time * 30 + begin_date, y = proportion, color = factor(status))) +
  geom_line() +
  labs(title = "SEIR",
       x = "Time",
       y = "Proportion of individuals",
       color = "Status") +
  labs(title='') +
  scale_color_manual(values = SEIR_colors) +
  # theme(axis.text.x=element_text(angle=45, hjust=1)) +
  theme_bw()
print(SEIR_p)
ggsave(file = file.path(fig_sim_path, 'SEIR', paste0(id_sim, "-SEIR-p.png")), plot = SEIR_p, height = 4, width = 20)
```




## Viral load over time
```{r}
dir.create(file.path(fig_sim_path, 'Viral-Load'))

viral_load_over_time <- do.call(rbind, lapply(1:(length(data_sim[["global_environment"]])%/% 10), function(t) {
  data.frame(time = begin_date + 30 * t*10,
             room = data_sim[["global_environment"]][[t*10]]$room,
             viral_load = data_sim[["global_environment"]][[t*10]]$env)
}))


viral_load_over_time <-  viral_load_over_time %>% left_join(rooms %>% select(room, volume) %>% distinct(room, .keep_all = T), by = join_by('room'))

VL_all <- ggplot(viral_load_over_time, aes(x = time, y = viral_load/volume, color = factor(room))) +
  geom_line() +
  labs(title = "",
       x = "Time",
       y = "Viral Load Concentration",
       color = "Room") +
  # theme(axis.text.x=element_text(angle=45, hjust=1)) +
  theme_bw() 
print(VL_all)
ggsave(file = file.path(fig_sim_path, 'Viral-Load', paste0(id_sim, "-Viral-Load-ALL.png")), plot = VL_all, height = 4, width = 20)


VL_no_room <- ggplot(viral_load_over_time %>% filter(!room %in% 1:17), aes(x = time, y = viral_load/volume, color = factor(room))) +
  geom_line() +
  labs(title = "",
       x = "Time",
       y = "Viral Load Concentration",
       color = "Room") +
  # theme(axis.text.x=element_text(angle=45, hjust=1)) +
  theme_bw() 

print(VL_no_room)
ggsave(file = file.path(fig_sim_path, 'Viral-Load', paste0(id_sim, "-Viral-Load-NO-ROOMS.png")), plot = VL_no_room, height = 4, width = 20)
```


## Viral load over time - Each room
```{r}
distinct_rooms <- viral_load_over_time %>% distinct(room) %>% pull()

for (id_room in distinct_rooms){
  VL_room <- ggplot(viral_load_over_time %>% filter(room == id_room), aes(x = time, y = viral_load/volume, color = factor(room))) +
    geom_line() +
    labs(title = paste0("Viral Load in Rooms Over Time - ", id_room),
         x = "Time",
         y = "Viral Load Concentration",
         color = "Room") +
    # theme(axis.text.x=element_text(angle=45, hjust=1)) +
    theme_bw() 
  print(VL_room)
  ggsave(file = file.path(fig_sim_path, "Viral-Load", paste0(id_sim, "-Viral-Load-Room-", id_room, ".png")), plot = VL_room, height = 4, width = 20)

}

distinct_rooms <- viral_load_over_time %>% distinct(room) %>% pull()
```

## FOR 1 DAY
```{r}
dir.create(file.path(fig_sim_path, 'Viral-Load-Day'))
## Arbitrary day -> 2020/06/05
arbitrary_day <- date('2020-06-05')

for (id_room in distinct_rooms){
  VL_room <- ggplot(viral_load_over_time %>%
                      filter(room == id_room) %>%
                      filter(date(time) == arbitrary_day),
                    aes(x = time, y = viral_load/volume, color = factor(room))) +
    geom_line() +
    labs(x = "Time",
         y = "Viral Load Concentration",
         title = paste0("Viral Load Concentration in Rooms Over Time - ", id_room),
         color = "Room") +
    # theme(axis.text.x=element_text(angle=45, hjust=1)) +
    theme_bw() 
  print(VL_room)
  ggsave(file = file.path(fig_sim_path, 'Viral-Load-Day', paste0(id_sim, "-Viral-Load-Day-Room-", id_room, ".png")), plot = VL_room, height = 4, width = 20)

}
```

```{r}
selected_rooms <- c('14', 'Nursing station', 'Paramedical Restroom')

p1 <- ggplot(viral_load_over_time %>% filter(room == selected_rooms[1]) %>% 
                      filter(date(time) == arbitrary_day),
                    aes(x = time, y = viral_load/volume, color = factor(room))) +
    geom_line(show.legend = FALSE) +
    labs(x = "Time",
         y = "Viral Load Concentration",
         title = selected_rooms[1],
         color = "Room") +
    theme(
      # axis.text.x=element_text(angle=45, hjust=1),
      legend.text=element_blank()) +
    theme_bw() 
p2 <- ggplot(viral_load_over_time %>% filter(room == selected_rooms[2]) %>% 
                      filter(date(time) == arbitrary_day),
                    aes(x = time, y = viral_load/volume, color = factor(room))) +
    geom_line(show.legend = FALSE) +
    labs(x = "Time",
         y = "Viral Load Concentration",
         title = selected_rooms[2],
         color = "Room") +
    theme(
      # axis.text.x=element_text(angle=45, hjust=1),
      legend.text=element_blank()) +
    theme_bw() 

p3 <- ggplot(viral_load_over_time %>% filter(room == selected_rooms[3]) %>% 
                      filter(date(time) == arbitrary_day),
                    aes(x = time, y = viral_load/volume, color = factor(room))) +
    geom_line(show.legend = FALSE) +
    labs(x = "Time",
         y = "Viral Load Concentration",
         title = selected_rooms[3],
         color = "Room") +
    theme(
      # axis.text.x=element_text(angle=45, hjust=1),
      legend.text=element_blank()) +
    theme_bw() 

print(p3)
p_viral <- cowplot::plot_grid(p1,p2,p3, labels = c("A ", "B ", "C "), nrow = 3, ncol = 1)
ggsave(filename = file.path(fig_sim_path, 'fig-selected-viral-load-day.png'), plot = p_viral, height = 12, width = 20)
```



## Lambda over time
```{r}
dir.create(file.path(fig_sim_path, 'Lambda'))
hcw_id <- admission_sim %>% filter(info == 1) %>% pull(id)

FOI_over_time <- do.call(rbind, lapply(1:(length(data_sim$global_data)%/% 100), function(t) {
  data.frame(time = begin_date + 30 * t*100,
             id = data_sim$global_data[[t*100]]$id,
             lambda_e = data_sim$global_data[[t*100]]$lambda_e,
             lambda_c = data_sim$global_data[[t*100]]$lambda_c,
             status = ifelse(data_sim$global_data[[t*100]]$id %in% hcw_id, "PE", "PA"))
}))

LAMBDA_p <- ggplot(FOI_over_time, aes(x = time)) +
  geom_line(aes(y = lambda_e, colour = "lambda_e (environment)" ), alpha = 0.5) +
  geom_line(aes(y = lambda_c, colour = "lambda_c (close-contact)" ), alpha = 0.5) +
  labs(title = "Lambda Over Time",
       x = "Time",
       y = "Lambda",
       color = "Lambda") +
  facet_grid(cols = vars(status)) + 
  theme_bw() + 
  theme(axis.text.x=element_text(angle=45, hjust=1))
print(LAMBDA_p)
ggsave(file = file.path(fig_sim_path, 'Lambda', paste0(id_sim, "-LAMBDA.png")), plot = LAMBDA_p, height = 4, width = 20)

```


## FOI over time
```{r}
dir.create(file.path(fig_sim_path, 'FOI'))
FOI_over_time <- FOI_over_time %>% mutate(p_inf = 1 - exp(-lambda_e - lambda_c))

FOI_p <- ggplot(FOI_over_time, aes(x = time)) +
  geom_line(aes(y = p_inf, colour = "P_inf" )) +
  labs(title = "Probability of infection Over Time",
       x = "Time",
       y = "P_inf",
       color = "P_inf") +
  facet_grid(cols = vars(status)) + 
  theme_bw() +
  theme(axis.text.x=element_text(angle=45, hjust=1))
print(FOI_p)
ggsave(file = file.path(fig_sim_path, 'FOI', paste0(id_sim, "-FOI.png")), plot = FOI_p, height = 4, width = 20)

```


## Individuals that stay susceptible
```{r}
list_S <- status_sim %>% filter(t_inf == -1) %>% select(id) %>% left_join(admission %>% select(id, cat, status), by= join_by(id))
write.csv2(x = list_S, file = file.path(fig_sim_path, paste0(id_sim, "list-susceptibles.csv")), row.names = F )
```


## Infection chain
```{r}
library(epicontacts)

HCW_interacting_ids <- admission %>% filter(status == "PE") %>% filter(id %in% id_interacting) %>% pull(id)
cat_paramedical <- c("nurse", "student nurse", "aux nurse")
cat_medical <- c("physician", "ext physician", "reeducation staff", "other")
id_paramedical <- admission %>% filter(id %in% HCW_interacting_ids & cat %in% cat_paramedical) %>% pull(id)
id_medical <- admission %>% filter(id %in% HCW_interacting_ids & cat %in% cat_medical) %>% pull(id)
# id_patient <- admission %>% filter(status == "PA") %>% filter(id %in% id_interacting) %>% pull(id)
id_patient <- admission_sim %>% filter(info == 0) %>% filter(id %in% id_interacting) %>% pull(id)
id_index <- status_sim %>% filter(inf_by == "INDEX") %>% pull(id)

## linelist object
linelist <- left_join(admission_sim %>% filter(id %in% id_interacting), status_sim, by = join_by(id))
linelist <- linelist %>% left_join(admission %>% select(id,cat), by = join_by(id))
linelist <- linelist %>%
  mutate(type = ifelse(id %in% id_medical , "MEDICAL", NA)) %>%
  mutate(type = ifelse(id %in% id_paramedical , "PARAMEDICAL", type)) %>%
  mutate(type = ifelse(id %in% id_patient , "PATIENT", type)) %>%
  mutate(type = ifelse(id == id_index, "INDEX", type)) %>%
  mutate(info = ifelse(info == 1, "HCW", "PATIENT")) %>% 
  mutate(room = case_when(
    type == 'MEDICAL' ~ 19,
    type == 'PARAMEDICAL' ~ 20,
    type == 'PATIENT' ~ room
  )) %>% 
  mutate(cat = ifelse(is.na(cat), 'patient', cat))


env_linelist <- data.frame(id = paste0("ENVIRONMENT-",rooms %>% distinct(id_room, .keep_all = TRUE) %>% pull(id_room)),
                           type = "ROOM",
                           room = rooms %>% distinct(id_room, .keep_all = TRUE) %>% pull(id_room),
                           info = rooms %>% distinct(id_room, .keep_all = TRUE) %>% pull(room))

linelist <- bind_rows(linelist,env_linelist)
linelist$type = factor(linelist$type, levels = c('INDEX', 'PATIENT', 'MEDICAL', 'PARAMEDICAL', 'ROOM'))

## contacts object
environmental_contacts <- status_sim %>%
  filter(grepl("ENVIRONMENT", inf_by)) %>%
  mutate(from = inf_by, to = id, time = t_inf) %>%
  mutate(cause = "ENVIRONMENT") %>% 
  select(from, to, t_inf, t_incub, t_recover, inf_by, cause)


close_contacts <- status_sim %>%
  filter(grepl("CONTACT", inf_by)) %>%
  mutate(from = gsub("CONTACT-", "", inf_by), to = id, time = t_inf) %>%
  mutate(cause = "CONTACT") %>% 
  select(from, to, t_inf, t_incub, t_recover, inf_by, cause)

inf_contacts_df <- bind_rows(environmental_contacts, close_contacts)
inf_contacts_df <- inf_contacts_df %>% mutate(inf_interval = paste0("{", t_inf, ";", t_incub, ";", t_inf, "}"))


## epicontacts object
x <- make_epicontacts(linelist = linelist,
                      contacts = inf_contacts_df,
                      id = "id",
                      from = "from",
                      to = "to",
                      directed = TRUE)

## plot epicontacts
sim_network <- vis_epicontacts(x,
                node_color = "type",
                edge_color = "cause",
                col_pal =  edges_pal,
                # edge_col_pal = spectral,
                # edge_label = "inf_interval",
                label = "room",
                node_shape = "type",
                shape = c(`PARAMEDICAL` = "circle", `MEDICAL` = "circle",  `PATIENT` = "circle", `ROOM` = "bed", `INDEX` = "circle"),
                thin = TRUE,
                selector = T
                )
sim_network


visSave(sim_network, file = file.path(fig_sim_path, paste0("infection-network.html")), selfcontained = T)
```
