---
title: "visualization-nodscov2"
author: "Olivier GAUFRÈS"
date: "2024-05-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(lubridate)
```

```{r}
wd <- getwd()
knitr::opts_chunk$set(root.dir = wd)
cpp_path <-  file.path(wd,"..", "..", "cpp")
cpp_model_path <- file.path(cpp_path,"nodscov2")
sim_nodscov2_path <- file.path(wd, "..", "..", "out", "sim-nodscov2")
```

```{r}
id_sim <- "01"
```

## TEST
```{r}
id_sim <- "test-endless-day"
load(file.path(sim_nodscov2_path, paste0(id_sim, "-", "simulation-nodscov2.RData")))
data_sim <- data_sim_test
rm(data_sim_test)

# global_interaction <- rep(truncated_interaction, n_days)
# global_localization <- rep(truncated_localization, n_days)
n_subdivisions <- new_n_subdivisions
begin_date <- new_begin_date
end_date <- new_end_date + days(n_days)
```

## REMOVE INDIVUDUALS NOT INTERACTING DURING THE SIMULATION
```{r}
id_interacting <- do.call(rbind,truncated_interaction) %>%
  pivot_longer(cols = c(from, to), names_to = "direction", values_to = "individual") %>%
  distinct(individual) %>%
  pull()
id_total <- admission %>% distinct(id) %>% pull()
id_not_interacting <- setdiff(id_total, id_interacting)
```

```{r}
status_sim <- data_sim[["global_status"]] %>% filter(id %in% id_interacting)
lambda_sim <- lapply(data_sim[["global_lambda"]], function(df)  df %>% filter(id %in% id_interacting))
#environment_sim <- data_sim[["global_environment"]] ## might filter it later to remove the rooms of patient not interacting in the truncated data
```



## Vizualisation
```{r}
## Number of infected over time
n_individual <- dim(status_sim)[1]
counts <- lapply(1:n_subdivisions, function(t) {
  df <- data.frame(status = c("Susceptible", "Exposed ", "Infectious", "Recovered"), count = NA, proportion = NA, time = t)
  
  df$count[1] <- sum(status_sim$t_inf == -1 | status_sim$t_inf > t)
  df$count[2] <- sum(status_sim$t_inf <= t & status_sim$t_incub > t)
  df$count[3] <- sum(status_sim$t_incub <= t & status_sim$t_recover > t)
  df$count[4] <- sum(status_sim$t_recover <= t & status_sim$t_inf != -1)
  
  df$proportion[1] <- df$count[1] * 100 / n_individual
  df$proportion[2] <- df$count[2] * 100 / n_individual
  df$proportion[3] <- df$count[3] * 100 / n_individual
  df$proportion[4] <- df$count[4] * 100 / n_individual
  
  return(df)
})

counts_df <- do.call(rbind, counts)

ggplot(counts_df, aes(x = time * 30 + begin_date, y = count, color = factor(status))) +
  geom_line() +
  labs(title = "SEIR",
       x = "Time",
       y = "Number of individuals",
       color = "Status") +
  theme_bw() +
  theme(axis.text.x=element_text(angle=45, hjust=1))

ggplot(counts_df, aes(x = time * 30 + begin_date, y = proportion, color = factor(status))) +
  geom_line() +
  labs(title = "SEIR",
       x = "Time",
       y = "Proportion of individuals",
       color = "Status") +
  theme_bw() +
  theme(axis.text.x=element_text(angle=45, hjust=1))
```

## Viral load
```{r}
viral_load_over_time <- do.call(rbind, lapply(1:(length(data_sim[["global_environment"]])%/% 10), function(t) {
  data.frame(time = begin_date + 30 * t*10,
             room = data_sim[["global_environment"]][[t*10]]$room,
             viral_load = data_sim[["global_environment"]][[t*10]]$env)
}))

ggplot(viral_load_over_time, aes(x = time, y = viral_load, color = factor(room))) +
  geom_line() +
  labs(title = "Viral Load in Rooms Over Time",
       x = "Time",
       y = "Viral Load",
       color = "Room") +
  theme_bw() +
  theme(axis.text.x=element_text(angle=45, hjust=1))
```


## FOI
```{r}
hcw_id <- admission %>% filter(status == "PE") %>% pull(id)


FOI_over_time <- do.call(rbind, lapply(1:(length(lambda_sim)%/% 100), function(t) {
  data.frame(time = begin_date + 30 * t*100,
             id = lambda_sim[[t*100]]$id,
             lambda_e = lambda_sim[[t*100]]$lambda_e,
             lambda_c = lambda_sim[[t*100]]$lambda_c,
             status = ifelse(lambda_sim[[t*100]]$id %in% hcw_id, "PE", "PA"))
}))

ggplot(FOI_over_time, aes(x = time)) +
  geom_line(aes(y = lambda_e, colour = "lambda_e (environment)" ), alpha = 0.5) +
  geom_line(aes(y = lambda_c, colour = "lambda_c (close-contact)" ), alpha = 0.5) +
  labs(title = "Lambda Over Time",
       x = "Time",
       y = "Lambda",
       color = "Lambda") +
  facet_grid(cols = vars(status)) + 
  theme_bw() + 
  theme(axis.text.x=element_text(angle=45, hjust=1))
```


```{r}
FOI_over_time <- FOI_over_time %>% mutate(p_inf = 1 - exp(-lambda_e - lambda_c))

ggplot(FOI_over_time, aes(x = time)) +
  geom_line(aes(y = lambda_e, colour = "P_inf" )) +
  labs(title = "Probability of infection Over Time",
       x = "Time",
       y = "P_inf",
       color = "P_inf") +
  facet_grid(cols = vars(status)) + 
  theme_bw() +
  theme(axis.text.x=element_text(angle=45, hjust=1))

```
## Individuals that stay susceptible
```{r}
list_S <- status_sim %>% filter(t_inf == -1) %>% select(id) %>% left_join(admission %>% select(id, cat, status), by= join_by(id))
```






## INFECTION CHAIN
```{r}
library(epicontacts)
id_index <- status_sim %>% filter(inf_by == "INDEX") %>% pull(id)
## linelist object
linelist <- left_join(admission_sim, status_sim, by = join_by(id))
linelist <- linelist %>%
  mutate(type = ifelse(info == 0, "PATIENT", "HEALTHCARE WORKER")) %>%
  mutate(type = ifelse(id == id_index, "INDEX", type)) 

env_linelist <- data.frame(id = paste0("ENVIRONMENT-",rooms %>% distinct(id_room, .keep_all = TRUE) %>% pull(id_room)),
                           type = "ROOM",
                           room = rooms %>% distinct(id_room, .keep_all = TRUE) %>% pull(id_room))

linelist <- bind_rows(linelist,env_linelist)


## contacts object
environmental_contacts <- status_sim %>%
  filter(grepl("ENVIRONMENT", inf_by)) %>%
  mutate(from = inf_by, to = id, time = t_inf) %>%
  mutate(cause = "ENVIRONMENT") %>% 
  select(from, to, t_inf, t_incub, t_recover, inf_by, cause)


close_contacts <- status_sim %>%
  filter(grepl("CONTACT", inf_by)) %>%
  mutate(from = gsub("CONTACT-", "", inf_by), to = id, time = t_inf) %>%
  mutate(cause = "CONTACT") %>% 
  select(from, to, t_inf, t_incub, t_recover, inf_by, cause)

inf_contacts_df <- bind_rows(environmental_contacts, close_contacts)
inf_contacts_df <- inf_contacts_df %>% mutate(inf_interval = paste0("{", t_inf, ";", t_incub, ";", t_inf, "}"))


## epicontacts object
x <- make_epicontacts(linelist = linelist,
                      contacts = inf_contacts_df,
                      id = "id",
                      from = "from",
                      to = "to",
                      directed = FALSE)

## plot epicontacts
vis_epicontacts(x,
                node_color = "type",
                edge_color = "cause",
                col_pal =  cases_pal,
                # edge_col_pal = spectral,
                # edge_label = "inf_interval",
                label = "room",
                node_shape = "type",
                shape = c(`HEALTHCARE WORKER` = "circle", `PATIENT` = "circle", `ROOM` = "bed", `INDEX` = "circle"),
                thin = TRUE,
                selector = TRUE
                )

### NOT WORKING
#node_colors <- setNames(c("red", "blue", "black","darkgreen"), c("PATIENT", "HEALTHCARE WORKER", "INDEX","ROOM"))
# custom_palette <- c("INDEX" = "#2ca02c", "PATIENT" = "#d62728", "HEALTHCARE WORKER" = "#1f77b4", "ROOM" = "#ff7f0e")
# linelist$color <- fac2col(linelist$type, pal = function(n) custom_palette)
```
