---
title: "interation-analysis"
author: "Olivier GAUFRÈS"
date: "2024-04-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(dplyr)
library(lubridate)
library(ggplot2)
```

## File paths
```{r}
wd <- getwd()
knitr::opts_chunk$set(root.dir = wd)
simplified_path <- file.path(wd,"..", "data","data-simplified")
```

## Graph build
```{r}
begin_date <- as.POSIXct("2009-07-06 00:00:00")
end_date <- as.POSIXct("2009-09-28 00:00:00")
time_spent <- end_date - begin_date
n_subdivisions <- as.integer(time_spent) * 24 * 60 * 2 ## Time spent * hours * minutes * 2 (number of time subdivisions)
```

## Data import
```{r}
knitr::opts_chunk$set(root.dir = wd)
observed_path <- file.path(wd,"..", "data","data-observed")
synthetic_path <- file.path(wd, "..", "data", "data-synthetic-graphs")
simplified_path <- file.path(wd, "..", "data", "data-simplified")
expanded_path <- file.path(wd,"..", "data","data-expanded")

admission <- read.csv2(file = file.path(simplified_path, "admission.csv"))

id_individual <- admission %>% distinct(id)

graph_1 <- read.csv2(file = file.path(simplified_path, "graph_1.csv"), header = TRUE, sep = ";") %>% 
                      mutate(date_posix = format(as.POSIXct(date_posix, tz="GMT"), format="%Y-%m-%d %H:%M:%S"))


#graph_tot <- read.csv2(file = file.path(expanded_path,"graph-1-int-1-to-end-R.csv"), header = TRUE)
```

```{r}
## Interaction's duration of 30sec
k = graph_1 %>% filter(length == 30) %>% mutate(from = gsub("-.*", "", from), to = gsub("-.*", "", to)) %>% select(-date_posix)
print("Interaction's duration of 30sec")
table(k$from, k$to)

## Proportions of interaction of 30s in all the int

print("Proportions of interaction of 30s")
prop.table(table(k$from, k$to))


print("Proportions of 30s int in all the int")
print(paste0(nrow(k)/nrow(graph_1) * 100, " %"))
```


```{r}
## Interaction's duration < 300sec
k = graph_1 %>% filter(length < 300) %>% mutate(from = gsub("-.*", "", from), to = gsub("-.*", "", to)) %>% select(-date_posix)
prop.table(table(k$from, k$to))
nrow(k)/nrow(graph_1)
```

```{r}
graph_1_nuit <- graph_1  %>%
  filter(hour(graph_1$date_posix) <= 4) %>%
  filter(length >= 300)
```


```{r}
## MENARD 1 HAS 28 BEDS
n_beds <- 28

tot <- NULL
## Nombre d'interaction minimales/maximales par jour --> cohérent avec le nombre de lits :)
for (i in 1:24){
  temp <- graph_1  %>% filter(hour(graph_1$date_posix) <=  4) %>%
  filter (length >= 60 * 5 * i) %>%
  group_by(date(date_posix)) %>%
  summarise(count = n(), count_distinct = length(unique(c(from, to)))) %>%
  summarise(min_count = min(count),
            max_count = max(count),
            min_distinct = min(count_distinct),
            max_distinct = max(count_distinct),
            count_under = sum((count_distinct) < n_beds))
  
  temp$time_night_s <- 60 * 5 * i
  temp$time_night_min <- i * 5
  tot <- bind_rows(tot, temp)
}
tot <- tot %>% select(time_night_min, min_count, max_count, min_distinct, max_distinct,count_under)


## ELBOW RULE TO FIND TIME

ggplot(data = tot) +
  geom_point(mapping = aes(x = time_night_min, y = min_count, color = "Minimum Count"), show.legend = FALSE) +
  geom_line(mapping = aes(x = time_night_min, y = min_count), linetype = "dashed") +
  
  geom_point(mapping = aes(x = time_night_min, y = max_count, color = "Maximum Count"), show.legend = FALSE) +
  geom_line(mapping = aes(x = time_night_min, y = max_count), linetype = "dashed") +
  
  geom_point(mapping = aes(x = time_night_min, y = min_distinct, color = "Minimum Distinct"), show.legend = FALSE) +
  geom_line(mapping = aes(x = time_night_min, y = min_distinct), linetype = "dashed") +
  
  geom_point(mapping = aes(x = time_night_min, y = max_distinct, color = "Maximum Distinct"), show.legend = FALSE) +
  geom_line(mapping = aes(x = time_night_min, y = max_distinct), linetype = "dashed") +
  
  scale_color_manual(values = c("Minimum Count" = "red", 
                                 "Maximum Count" = "darkred",
                                 "Minimum Distinct" = "blue",
                                 "Maximum Distinct" = "darkblue")) +
  labs( x = "Time (min)", y = "Interactions (red) & Distinct individuals (blue)") +
  labs(title = "Interactions at night in Menard 1") +
  theme(legend.position = "top")

print(tot)

## issue w/ the colors???


```

## Filtration according to these assumptions
```{r}
## WE CHOOSE TO HAVE MORE INTERACTIONS THAN DISTINCT INDIVIDUALS INTERACTING
## WE CHOOSE TO SET THE THRESHOLD OF LENGTH FOR A NIGHT INTERACTION TO 45 minutes -> 2700 seconds

length_thresold <- 45 * 60
hour_thresold <- 4

## Inspection
test_graph <- graph_1  %>%
  filter(hour(graph_1$date_posix) <= hour_thresold) %>%
  filter(length >= length_thresold) %>% filter( date(date_posix) == date(begin_date)) 

test_unique <- unique(c(test_graph$from,test_graph$to))

admission_modified <- admission %>% mutate(lastDate = ifelse(nchar(lastDate) == 0, "2999-01-01", lastDate))
ind_present <- graph_1 %>% group_by(date(date_posix)) %>% select(-c(from,to,length,date_posix)) %>% distinct



graph_1_nuit <- graph_1  %>%
  filter(hour(graph_1$date_posix) <= hour_thresold) %>%
  filter(length >= length_thresold)

```





```{r}
## Inference of a possible localisation of those who interact for more than 10 mins during the night 
graph_1_bis <- graph_1  %>% filter(hour(graph_1$date_posix) <=  hour_thresold) %>%
  filter (length >= length_thresold) %>%
  group_by(date(date_posix)) %>% mutate(localisation = case_when((gsub("-.*", "", from) == "PA" & gsub("-.*", "", to) == "PE") ~ "chambrePA-from",
                                                                 (gsub("-.*", "", from) == "PE" & gsub("-.*", "", to) == "PA") ~ "chambrePA-to",
                                                                 (gsub("-.*", "", from) == "PA" & gsub("-.*", "", to) == "PA") ~ "sameroom",
                                                                 (gsub("-.*", "", from) == "PE" & gsub("-.*", "", to) == "PE") ~ "restroom")) %>%
  mutate(from_n = pmin(from,to), to_n = pmax(from, to)) %>% 
  select(-c("to","from")) 



graph_1  %>% filter(hour(graph_1$date_posix) <=  hour_thresold) %>%
  filter (length >= length_thresold) %>% 
  group_by(date(date_posix)) %>%
  mutate(localisation = case_when((gsub("-.*", "", from) == "PA" & gsub("-.*", "", to) == "PE") ~ "chambrePA-from",
                                                                 (gsub("-.*", "", from) == "PE" & gsub("-.*", "", to) == "PA") ~ "chambrePA-to",
                                                                 (gsub("-.*", "", from) == "PA" & gsub("-.*", "", to) == "PA") ~ "sameroom",
                                                                 (gsub("-.*", "", from) == "PE" & gsub("-.*", "", to) == "PE") ~ "restroom")) %>%
  mutate(from_n = pmin(from,to), to_n = pmax(from, to)) %>% 
  select(-c("to","from")) %>%
  ungroup() %>%
  group_by(localisation) %>%
  summarise()








# Autre façon de définir une nuit
# graph_1_nuit <- graph_1  %>% filter(hour(graph_1$date_posix) >= 18 | hour(graph_1$date_posix + graph_1$length) <= 5 )
```


## Conditions
```{r}
#  ## Interactions between HCW & Patients take place in patient's room (FROM = PA AND TO = PE)
# cond1 = substr(from, 1, 2) == "PA" && substr(to, 1, 2) == "PE" 
# 
# ## Interactions between HCW & Patients take place in patient's room (FROM = PE AND TO = PA)
# cond2 = substr(from, 1, 2) == "PE" && substr(to, 1, 2) == "PA"
#    
# ## Interactions between patients take place in the corridor
#  cond3 = substr(from, 1, 2) == "PA" && substr(to, 1, 2) == "PA"
#       
# ## Interactions between HCW take place in the HCW's rest room
# cond4 = substr(from, 1, 2) == "PE" && substr(to, 1, 2) == "PE" 
```


```{r}
## set de condition pour assigner à une chambre
graph1 %>%
mutate(localisation = case_when(cond1 ~ "chambre1",
                                cond2 ~ "chambre2",
                                cond3 ~ "chambre3",
                                cond4 ~ "chambre4",
                                cond5 ~ "chambre5",
                                cond6 ~ "chambre6",
                                cond7 ~ "chambre7",
                                cond8 ~ "chambre8",
                                cond9 ~ "chambre9",
                                cond10 ~ "chambre10",
                                cond11 ~ "chambre11",
                                cond12 ~ "chambre12",
                                cond13 ~ "chambre13",
                                cond14 ~ "chambre14",
                                cond15 ~ "chambre15",
                                cond16 ~ "chambre16",
                                cond17 ~ "chambre17",
                                cond18 ~ "chambre18",
                                cond19 ~ "chambre19",
                                cond20 ~ "chambre20",
                                cond21 ~ "chambre21",
                                cond22 ~ "chambre22",
                                cond23 ~ "chambre23",
                                cond24 ~ "chambre24",
                                cond25 ~ "chambre25",
                                cond26 ~ "chambre26",
                                cond27 ~ "chambre27",
                                cond28 ~ "chambre28",
                                cond24 ~ "corridor",
                                cond25 ~ "restroom",))
```















#####################################################################
#################### GARBAGE ########################################
#####################################################################

```{r}
##Interactions ayant lieu chaque "nuit" 
# graph_1  %>% filter(hour(graph_1$date_posix) <=  5) %>%
#   filter (length >= 500) %>%
#   group_by(date(date_posix)) %>% mutate(localisation = case_when(substr(from, 1, 2) == "PA" && substr(to, 1, 2) == "PE" ~ "chambre",
#                                                                  substr(from, 1, 2) == "PE" && substr(to, 1, 2) == "PA" ~ "chambre",
#                                                                  substr(from, 1, 2) == "PA" && substr(to, 1, 2) == "PA" ~ "restroom",
#                                                                  substr(from, 1, 2) == "PE" && substr(to, 1, 2) == "PE" ~ "corridor"))

```


```{r}
# 
# ## CALCUL SUR 84J TROP LONG -> SUR UN JOUR/SEMAINE
# n_jour <- 24 * 60 * 2 
# n_semaine <- 24 * 60 * 2 * 7
# 
# 
# # Get unique subdivisions of time (dates)
# unique_dates <- unique(graph_tot$time)
# # Liste de DF pour chaque individus à chaque subdivision de temps
# interaction_list <- list()
# time_a <- Sys.time()
# # Boucle sur 1:n_subdivision (ici différent pour voir si fonctionnel)
# for (time in 1:n_semaine) {
#   # interactions à la subdivision t=time
#   df_time <- graph_tot[graph_tot$time == time, ]
#   # listes des
#   unique_individuals <- unique(c(df_time$from, df_time$to))
#   
#   # Boucle sur ces individus
#   for (ide in unique_individuals) {
#     # Interactions de l'individu
#     df_id_time <- df_time[df_time$from == ide | df_time$to == ide, ]
#     
#     # On check si l'individu a plusieurs interactions au même moment t=time
#     if (nrow(df_id_time) > 1) {
#       # On place ces interactions dans en spécifiant le time interaction_list
#       interaction_list[[paste0("int_", ide, "_", time)]] <- df_id_time
#     }
#   }
# }
# time_b <- Sys.time()
# print(time_b-time_a)
# 
# # on cherche les interaction d'un id au temps t de la façon suivante: interaction8list[["id_t"]] 
# # ex interaction de: "PA-065-CAD" au temps t: "122":
# int_PA_065_CAD_122 <- interaction_list[["int_PA-065-CAD_122"]]

```





## Multiple interaction
```{r}
## Interactions for each individual

# for (ind in id_individual$id){
#   int_ind <- graph_1 %>% filter(ind == from | ind == to)
#   assign(paste0("int_", ind), int_ind)
# }
```





```{r}
# for (ide in admission %>% distinct(id) %>% pull(id) ){
#   assign(paste0("int_",ide), data.frame(NULL))
# }
# 
# for (time in graph_tot$time){
#   df_id_time <- data.frame(id = graph_tot[graph_tot$time == time, "from"]) %>% add_row(data.frame(id = graph_tot[graph_tot$time == time, "to"]))
#   for (ide in df_id_time$id){
#     if ( dim(df_id_time %>% filter(id == ide))[1]  > 1){
#       assign(paste0("int_",ide), graph_tot %>% filter(graph_tot$time == time) %>% filter(from == ide | to == ide))
#     }
#   }
# }
```


```{r}
#graph_tot %>% group_by(time) %>% summarise(n = 2*n(), n_ind_multi =  length(unique(c(from, to))), .groups = "drop")

## n = number of individuals interacting at each time, n_ind_multi = number of unique couples {from,to} in each time
# out = graph_tot %>% group_by(time) %>% summarise(n = 2*n(), n_ind_multi =  length(unique(c(from, to))), .groups = "drop") 
# 
# time_multiple <- out %>% filter(out$n != out$n_ind_multi) %>% pull(time)
# nb_multiple <-  out %>% filter(out$n != out$n_ind_multi) %>% mutate()
# 
# ## Total nb of time
# nrow(out)
# ## Nb of time theres a multiple interaction
# sum(out$n != out$n_ind_multi)
# 
# ## Number of time their is only unique interactions
# print(nrow(out) - sum(out$n != out$n_ind_multi))
# out <- NULL
```

```{r}
# out = graph_tot %>% group_by(time)
```






## TEST
```{r}

# graph_1 <- graph_1 %>%
#   mutate(interaction_pair = paste0(pmin(from, to), "-", pmax(from, to)))
# 
# graph_tot <- graph_tot %>%
#   mutate(interaction_pair = paste0(pmin(from, to), "-", pmax(from, to)))

##NOT WORKING 
# # Group by date_posix and interaction_pair, count the number of interactions
# multiple_interactions <- graph_tot_bis %>%
#   group_by(time, interaction_pair) %>%
#   summarise(num_interactions = n()) %>%
#   #filter(num_interactions > 1) %>%
#   summarise(n = 2*n(),num_individuals = n_distinct(interaction_pair), .groups = "drop")





# # Group by date_posix and interaction_pair, count the number of interactions
# multiple_interactions <- graph_bis %>%
#   group_by(date_posix, interaction_pair) %>%
#   summarise(num_interactions = n()) %>%
#   filter(num_interactions > 1) %>%
#   summarise(num_individuals = n_distinct(interaction_pair))
# 

```
```{r}
# # Self-join the dataframe to compare interactions within the same time range
# multiple_interactions <- graph_1 %>%
#   inner_join(graph_1, by = NULL) %>%
#   filter(graph_1$from != to | graph_1$to != from) %>%
#   filter(graph_1$date_posix == date_posix | 
#            (graph_1$date_posix <= date_posix + as.numeric(length) & graph_1$date_posix + as.numeric(graph_1$length) >= date_posix)) %>%
#   group_by(from, date_posix) %>%
#   summarise(num_interactions = n_distinct(to)) %>%
#   filter(num_interactions > 1) %>%
#   summarise(num_individuals = n_distinct(from))

```






































