---
---
title: "observed-vs-synthetic"
author: "Olivier GAUFRÈS"
date: "2024-04-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(dplyr)
library(lubridate)
library(ggplot2)
```

## File paths
```{r}
wd <- getwd()
knitr::opts_chunk$set(root.dir = wd)
observed_path <- file.path(wd,"..", "data","data-observed")
synthetic_path <- file.path(wd, "..", "data", "data-synthetic-graphs")
simplified_path <- file.path(wd, "..", "data", "data-simplified")
expanded_path <- file.path(wd,"..", "data","data-expanded")
```

## i-Bird study data
```{r}
begin_date <- as.POSIXct("2009-07-06 00:00:00", tz="GMT")
end_date <- as.POSIXct("2009-09-28 00:00:00", tz="GMT")
time_spent <- end_date - begin_date
n_subdivisions <- as.integer(time_spent) * 24 * 60 * 2 ## Time spent * hours * minutes * 2 (number of time subdivisions)
```

## Data import
```{r}
## NA when the individual is still in the hospital --> we fill these NAs
admission <- read.csv2(file = file.path(simplified_path, "admission.csv"))
admission <- admission %>% mutate(lastDate = ifelse(nchar(lastDate) == 0, "2999-01-01", lastDate))
admission <- admission %>% mutate(firstDate = as.POSIXct(firstDate, tz="GMT"), lastDate = as.POSIXct(lastDate, tz="GMT") ) 
admission <- admission %>% filter(!lastDate < begin_date)  ## unnecessary data
admission <- admission %>% filter(!firstDate > end_date) ## unnecessary data


## id of all individuals in the 84 days range
id_individual <- admission %>% distinct(id)

## MENARD 1 HAS 28 BEDS
n_beds <- 28

## Observed data from i-Bird study
observed <- read.csv2(file = file.path(simplified_path, "mat_ctc.csv"), header = TRUE, sep = ";") %>% 
                      mutate(date_posix = as.POSIXct(date_posix, tz="GMT"))

synthetic <- read.csv2(file = file.path(simplified_path, "graph_1.csv"), header = TRUE, sep = ";") %>% 
                      mutate(date_posix = as.POSIXct(date_posix, tz="GMT"))



## Date range of 84 days ($time_spent)
observed <- observed  %>% filter(date(date_posix) <= date(end_date))%>% filter(date(date_posix) >= date(begin_date))
synthetic <- synthetic  %>% filter(date(date_posix) <= date(end_date))%>% filter(date(date_posix) >= date(begin_date))
```


```{r}
tot <- NULL
## Range of amount of interactions happening at night + distinct individuals involved + number of days there is less than n_beds individuals interacting at night
for (i in 0:60){
  temp <- observed  %>% filter(hour(observed$date_posix) <=  5 | hour(observed$date_posix) >= 22)  %>%
  filter (length >= 60 * 5 * i) %>%
  group_by(date(date_posix)) %>%
  summarise(count = n(), count_distinct = length(unique(c(from, to)))) %>%
  summarise(min_count = min(count),
            median_count = median(count),
            max_count = max(count),
            min_distinct = min(count_distinct),
            median_distinct = median(count_distinct),
            max_distinct = max(count_distinct),
            count_under_beds = sum((count_distinct) < n_beds)
            )
  
  temp$time_night_s <- 60 * 5 * i
  temp$time_night_min <- i * 5
  tot <- bind_rows(tot, temp)
  rm(temp)
}

tot <- tot %>% select(time_night_min,
                      min_count,
                      median_count,
                      max_count,
                      min_distinct,
                      median_distinct,
                      max_distinct,
                      count_under_beds)


## ELBOW RULE TO FIND TIME

ggplot(data = tot[1:30,]) +
#ggplot(data = tot) +
  geom_point(mapping = aes(x = time_night_min, y = min_count, color = "Minimum Count"), show.legend = TRUE) +
  geom_line(mapping = aes(x = time_night_min, y = min_count), linetype = "dashed") +
  
  geom_point(mapping = aes(x = time_night_min, y = max_count, color = "Maximum Count"), show.legend = TRUE) +
  geom_line(mapping = aes(x = time_night_min, y = max_count), linetype = "dashed") +
  
  geom_point(mapping = aes(x = time_night_min, y = min_distinct, color = "Minimum Distinct"), show.legend = TRUE) +
  geom_line(mapping = aes(x = time_night_min, y = min_distinct), linetype = "dashed") +
  
  geom_point(mapping = aes(x = time_night_min, y = max_distinct, color = "Maximum Distinct"), show.legend = TRUE) +
  geom_line(mapping = aes(x = time_night_min, y = max_distinct), linetype = "dashed") +
  
  scale_color_manual(values = c("Minimum Count" = "red", 
                                 "Maximum Count" = "darkred",
                                 "Minimum Distinct" = "blue",
                                 "Maximum Distinct" = "darkblue")) +
  xlim(0, 150) + ylim(0, 500) +
  labs( x = "Time (min)", y = "Interactions (red) & Distinct individuals (blue)") +
  labs(title = "Interactions at night in Menard 1 - Observed data") +
  #scale_y_continuous(trans = "log10") +
  theme(legend.position = "top")

print(tot)
```


```{r}
tot <- NULL
## Range of amount of interactions happening at night + distinct individuals involved + number of days there is less than n_beds individuals interacting at night
for (i in 0:60){
  temp <- synthetic  %>% filter(hour(synthetic$date_posix) <=  5 | hour(synthetic$date_posix) >= 22)  %>%
  filter (length >= 60 * 5 * i) %>%
  group_by(date(date_posix)) %>%
  summarise(count = n(), count_distinct = length(unique(c(from, to)))) %>%
  summarise(min_count = min(count),
            median_count = median(count),
            max_count = max(count),
            min_distinct = min(count_distinct),
            median_distinct = median(count_distinct),
            max_distinct = max(count_distinct),
            count_under_beds = sum((count_distinct) < n_beds)
            )
  
  temp$time_night_s <- 60 * 5 * i
  temp$time_night_min <- i * 5
  tot <- bind_rows(tot, temp)
  rm(temp)
}

tot <- tot %>% select(time_night_min,
                      min_count,
                      median_count,
                      max_count,
                      min_distinct,
                      median_distinct,
                      max_distinct,
                      count_under_beds)


## ELBOW RULE TO FIND TIME

ggplot(data = tot[1:30,]) +
#ggplot(data = tot) +
  geom_point(mapping = aes(x = time_night_min, y = min_count, color = "Minimum Count"), show.legend = TRUE) +
  geom_line(mapping = aes(x = time_night_min, y = min_count), linetype = "dashed") +
  
  geom_point(mapping = aes(x = time_night_min, y = max_count, color = "Maximum Count"), show.legend = TRUE) +
  geom_line(mapping = aes(x = time_night_min, y = max_count), linetype = "dashed") +
  
  geom_point(mapping = aes(x = time_night_min, y = min_distinct, color = "Minimum Distinct"), show.legend = TRUE) +
  geom_line(mapping = aes(x = time_night_min, y = min_distinct), linetype = "dashed") +
  
  geom_point(mapping = aes(x = time_night_min, y = max_distinct, color = "Maximum Distinct"), show.legend = TRUE) +
  geom_line(mapping = aes(x = time_night_min, y = max_distinct), linetype = "dashed") +
  
  scale_color_manual(values = c("Minimum Count" = "red", 
                                 "Maximum Count" = "darkred",
                                 "Minimum Distinct" = "blue",
                                 "Maximum Distinct" = "darkblue")) +
  xlim(0, 150) + ylim(0, 500) +
  labs( x = "Time (min)", y = "Interactions (red) & Distinct individuals (blue)") +
  labs(title = "Interactions at night in Menard 1 - Synthetic data") +
  #scale_y_continuous(trans = "log10") +
  theme(legend.position = "top")

print(tot)
## issue w/ the colors???


```

## Length distribution during night
```{r}

temp_o <- observed  %>% filter(hour(observed$date_posix) <=  5 | hour(observed$date_posix) >= 22)  
temp_s <- synthetic  %>% filter(hour(synthetic$date_posix) <=  5 | hour(synthetic$date_posix) >= 22)  

data_g <- data.frame(observed_l = temp_o$length, synthethic_l = temp_s$length)

ggplot(temp_o, aes(x=length)) +
    geom_histogram(binwidth=.5, colour="black", fill="white") +
    scale_x_continuous(trans = "log2", limits = c(0.1,70000))+
    ylim(0, 50000) +
    geom_vline(aes(xintercept=mean(length)),   # Ignore NA values for mean
               color="red", linetype="dashed", size=1)


ggplot(temp_s, aes(x=length)) +
    geom_histogram(binwidth=.5, colour="black", fill="white") +
    scale_x_continuous(trans = "log2", limits = c(0.1,70000))+
    ylim(0, 50000) +
    geom_vline(aes(xintercept=mean(length)),   # Ignore NA values for mean
               color="red", linetype="dashed", size=1)


```

